# Generated by Django 5.2.15 on 2026-06-28 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlacklistedFirm",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("firm_name", models.CharField(db_index=True, max_length=500)),
                (
                    "proprietor_name",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "blacklist_date_bs",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "blacklist_date_ad",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "effective_until_bs",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "effective_until_ad",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("duration", models.CharField(blank=True, max_length=100, null=True)),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "recommending_office",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "nes_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "blacklisted_firms",
            },
        ),
        migrations.CreateModel(
            name="Court",
            fields=[
                (
                    "identifier",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("court_type", models.CharField(db_index=True, max_length=20)),
                ("full_name_nepali", models.CharField(max_length=200)),
                (
                    "full_name_english",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "courts",
            },
        ),
        migrations.CreateModel(
            name="CaseEntity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("case_number", models.CharField(db_index=True, max_length=50)),
                ("side", models.CharField(db_index=True, max_length=20)),
                ("name", models.CharField(max_length=500)),
                ("address", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "nes_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "court",
                    models.ForeignKey(
                        db_column="court_identifier",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="case_entities",
                        to="courts.court",
                    ),
                ),
            ],
            options={
                "db_table": "court_case_entities",
            },
        ),
        migrations.CreateModel(
            name="CourtCase",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "case_number",
                        "court",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("case_number", models.CharField(db_index=True, max_length=50)),
                (
                    "registration_date_bs",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "registration_date_ad",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "case_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=200, null=True
                    ),
                ),
                (
                    "case_status",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("plaintiff", models.TextField(blank=True, null=True)),
                ("defendant", models.TextField(blank=True, null=True)),
                (
                    "nes_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("extra_data", models.JSONField(blank=True, null=True)),
                ("document_sources", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "court",
                    models.ForeignKey(
                        db_column="court_identifier",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="cases",
                        to="courts.court",
                    ),
                ),
            ],
            options={
                "db_table": "court_cases",
            },
        ),
        migrations.CreateModel(
            name="CourtCaseHearing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("case_number", models.CharField(db_index=True, max_length=50)),
                ("hearing_date_bs", models.CharField(db_index=True, max_length=20)),
                ("hearing_date_ad", models.DateField(db_index=True)),
                ("bench", models.CharField(blank=True, max_length=100, null=True)),
                ("bench_type", models.CharField(blank=True, max_length=100, null=True)),
                ("judge_names", models.TextField(blank=True, null=True)),
                ("lawyer_names", models.TextField(blank=True, null=True)),
                ("serial_no", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "case_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "decision_type",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("scraped_at", models.DateTimeField()),
                ("extra_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "court",
                    models.ForeignKey(
                        db_column="court_identifier",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="hearings",
                        to="courts.court",
                    ),
                ),
            ],
            options={
                "db_table": "court_case_hearings",
            },
        ),
    ]
