# Generated by Django 5.2.15 on 2026-07-30 21:15
#
# APPLY THIS FOR REAL — do not --fake it. Most courts migrations are faked in prod
# because their tables were created outside Django (see the note in courts/models.py),
# but court_register_probes is genuinely new. Faking it leaves the table missing and
# the register sweep dies on the first absent docket it tries to record.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0006_blacklistedfirm_uniq_blacklisted_firm_name_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterProbe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('case_number', models.CharField(db_index=True, max_length=50)),
                ('miss_count', models.IntegerField(default=1)),
                ('last_probed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('court', models.ForeignKey(db_column='court_identifier', on_delete=django.db.models.deletion.DO_NOTHING, related_name='register_probes', to='courts.court')),
            ],
            options={
                'db_table': 'court_register_probes',
                'constraints': [models.UniqueConstraint(fields=('court', 'case_number'), name='uniq_register_probe')],
            },
        ),
    ]
