# Generated by Django 5.2.8 on 2025-11-27 01:54

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_documentsource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="alleged_entities",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of entity IDs for entities being accused",
            ),
        ),
        migrations.AlterField(
            model_name="documentsource",
            name="description",
            field=models.TextField(blank=True, help_text="Source description"),
        ),
    ]
