# Generated by Django 5.2.9 on 2026-05-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0019_add_publication_date_to_documentsource"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="financials",
            field=models.JSONField(
                blank=True,
                help_text="Financial details of the case (alleged amount, recovered, fines, etc.)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="narrative",
            field=models.JSONField(
                blank=True,
                help_text="Structured narrative fields for public display and social cards",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="outcomes",
            field=models.JSONField(
                blank=True,
                help_text="Final outcomes and verdict details of the case",
                null=True,
            ),
        ),
    ]
