# Generated by Django 5.2.9 on 2026-05-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0020_remove_promises_case_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="description",
            field=models.TextField(
                blank=True, help_text="Markdown description of the case"
            ),
        ),
    ]
