# Generated by Django 5.2.9 on 2026-05-13 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0021_alter_case_description"),
        ("cases", "0021_enforce_slug_not_null"),
    ]

    operations = []
