# Generated by Django 5.2.9 on 2026-05-16 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0023_chat_user_identity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatuseridentity",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this identity mapping was created"
            ),
        ),
        migrations.AlterField(
            model_name="chatuseridentity",
            name="owui_user_id",
            field=models.CharField(
                db_index=True,
                help_text="Chat system user identifier (e.g., OpenWebUI user ID)",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="chatuseridentity",
            name="user",
            field=models.ForeignKey(
                help_text="Django user associated with this chat identity",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_identities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
