# Generated by Django 5.2.9

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0026_merge_20260611_0704"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentsource",
            name="link_types",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Parallel array to url — link type per URL. Values: RAW, PERMALINK, MARKDOWN",
            ),
        ),
    ]
