# Generated by Django 5.2.9 on 2026-06-11 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0027_drop_caseworker_tables"),
        ("cases", "0028_alter_source_type_choices"),
    ]

    operations = []
