# Generated by Django 5.2.9 on 2026-06-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0030_backfill_null_source_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentsource",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("CIAA_PRESS_RELEASE", "CIAA Press Release"),
                    ("AG_ABHIYOG_PATRA", "AG Charge Sheet (Abhiyog Patra)"),
                    ("OAG_AUDIT_REPORT", "OAG Audit Report"),
                    ("COURT_ORDER", "Court Order/Verdict"),
                    ("COURT_FILING_OTHER", "Other Court Filing"),
                    ("LAW_OR_BILL", "Law/Act/Bill"),
                    ("NEWS", "News/Media"),
                    ("SOCIAL_MEDIA", "Social Media"),
                    ("MISC", "Miscellaneous"),
                ],
                default="MISC",
                help_text="Type of source",
                max_length=50,
            ),
        ),
    ]
