# Generated by Django 5.2.9 on 2026-06-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0032_backfill_source_link_role_raw"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="case_type",
            field=models.CharField(
                choices=[("CORRUPTION", "Corruption"), ("TAX_EVASION", "Tax Evasion")],
                help_text="Type of case",
                max_length=20,
            ),
        ),
    ]
