# Generated by Django 5.2.9 on 2026-06-12 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0033_alter_case_case_type"),
        ("cases", "0033_drop_uploaded_file_machinery"),
    ]

    operations = []
