# Generated by Django 5.2.9 on 2026-06-13 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0034_merge_20260612_0646"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="case_type",
            field=models.CharField(
                choices=[
                    ("CORRUPTION", "Corruption (भ्रष्टाचार)"),
                    ("BRIBERY", "Bribery (घूस)"),
                    ("FORGERY", "Forgery (नक्कली)"),
                    ("EMBEZZLEMENT", "Embezzlement (अपचय)"),
                    ("ABUSE_OF_OFFICE", "Abuse of Office (दुरुपयोग)"),
                    ("MONEY_LAUNDERING", "Money Laundering (सम्पत्ति शुद्धीकरण)"),
                    ("ILLEGAL_PROPERTY", "Illegal Property (गैरकानूनी सम्पत्ति)"),
                    ("EXAM_RIGGING", "Exam Rigging (परीक्षा अनियमितता)"),
                    ("TAX_EVASION", "Tax Evasion (कर छली)"),
                ],
                help_text="Type of case",
                max_length=32,
            ),
        ),
    ]
