# Generated by Django 5.2.9 on 2026-06-17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0033_archive_search_indexes"),
        ("cases", "0035_add_corruption_derived_case_types"),
    ]

    operations = []
