# Generated by Django 5.2.9 on 2026-06-17 05:05

import django.db.models.deletion
from django.db import migrations, models

import cases.models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0036_merge_archive_search_case_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentSourceUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded file",
                        upload_to="jawafdehi/sources/%Y/%m/%d/",
                        validators=[
                            cases.models.validate_upload_file_extension,
                            cases.models.validate_upload_file_size,
                            cases.models.validate_upload_file_mimetype,
                        ],
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        blank=True,
                        help_text="Original filename (auto-populated)",
                        max_length=255,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True,
                        help_text="MIME type (auto-populated best-effort)",
                        max_length=100,
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="File size in bytes (auto-populated)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        help_text="Document source this uploaded file belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_files",
                        to="cases.documentsource",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
