# Generated by Django 5.2.9 on 2026-06-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0036_delete_chatuseridentity"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="internal_notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Internal-only notes; not exposed via the public API.",
            ),
        ),
    ]
