# Generated by Django 5.2.15 on 2026-06-28 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0037_alter_documentsource_related_entities"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="case_id",
        ),
    ]
