# Generated by Django 5.2.15 on 2026-07-01 16:28

import cases.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0040_drop_case_workflows_tables"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseMaterialReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_iri",
                    models.CharField(
                        db_index=True,
                        help_text="Canonical NGM material @id IRI (https://jawafdehi.org/material/<source>/<ident>) cited as evidence. NGM owns the document data; this is the join key only.",
                        max_length=300,
                        validators=[cases.models.validate_material_iri],
                    ),
                ),
                (
                    "additional_details",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional case-specific note on why this material matters to this case (distinct from the material's own global description).",
                    ),
                ),
                (
                    "ordinal",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order of this evidence reference within the case.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this evidence reference was created",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        help_text="The case this evidence reference belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_references",
                        to="cases.case",
                    ),
                ),
            ],
            options={
                "verbose_name": "Case Material Reference",
                "verbose_name_plural": "Case Material References",
                "ordering": ["ordinal", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["case", "ordinal"], name="case_material_ordinal_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("case", "material_iri"),
                        name="unique_case_material_reference",
                    )
                ],
            },
        ),
    ]
