# Generated by Django 5.2.15 on 2026-07-01 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0041_casematerialreference"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="evidence",
        ),
        migrations.DeleteModel(
            name="DocumentSource",
        ),
    ]
