# Generated by Django 5.2.15 on 2026-07-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0043_alter_case_case_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsSnapshot',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('data', models.JSONField(help_text='The exact JSON payload served by /api/statistics/')),
                ('computed_at', models.DateTimeField(help_text='When this payload was computed (also carried as last_updated inside data)')),
            ],
            options={
                'verbose_name': 'Statistics Snapshot',
                'verbose_name_plural': 'Statistics Snapshots',
            },
        ),
    ]
