# Generated by Django 5.2.15 on 2026-07-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0044_statisticssnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticssnapshot',
            name='is_placeholder',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
