# Generated by Django 5.2.15 on 2026-07-03 19:54
#
# court_cases JSONField -> CaseCourtCaseReference join keyed by the canonical
# court-case @id IRI. Ordered: create the join table, copy the legacy
# "<court>:<case_number>" refs into it as IRIs, then drop the JSONField.

import cases.validators
import django.db.models.deletion
from django.db import migrations, models, router

from cases.validators import VALID_COURT_IDENTIFIERS
from jawafdehi_shared.entities.ids import build_courtcase_iri, parse_courtcase_iri


def _copy_court_cases_to_join(apps, schema_editor):
    """Rewrite each case's court_cases JSON refs as join rows keyed by IRI.

    Best-effort per ref, but NEVER silently lossy: a ref that cannot become a
    valid join row — malformed, unknown court (post-migration validation
    would reject its IRI, 422-ing every later PATCH of the case), or a case
    number outside the IRI grammar (the 2026-07-06 prod audit found one: an
    NKP citation stored as a ref) — is preserved verbatim in the case's
    ``missing_details``, because the RemoveField in this same migration drops
    the JSON column right after.
    """
    db = schema_editor.connection.alias
    Case = apps.get_model("cases", "Case")
    Reference = apps.get_model("cases", "CaseCourtCaseReference")
    if not router.allow_migrate_model(db, Reference):
        return
    rows = []
    for case in Case.objects.using(db).exclude(court_cases__isnull=True).iterator():
        ordinal = 0
        seen = set()
        unmigrated = []
        for ref in case.court_cases or []:
            iri = None
            if isinstance(ref, str) and "://" not in ref and ref.count(":") == 1:
                court, _, number = ref.partition(":")
                if court.strip().lower() in VALID_COURT_IDENTIFIERS:
                    try:
                        iri = build_courtcase_iri(court.strip(), number.strip())
                    except ValueError:
                        iri = None
            if iri is None:
                print(
                    f"  [0046] case pk={case.pk}: court_cases ref {ref!r} not "
                    "canonicalizable — preserving in missing_details"
                )
                unmigrated.append(str(ref))
                continue
            if iri in seen:
                continue
            seen.add(iri)
            rows.append(Reference(case=case, courtcase_iri=iri, ordinal=ordinal))
            ordinal += 1
        if unmigrated:
            note = (
                "Court-case refs not migrated to @id IRIs (kept verbatim): "
                + "; ".join(unmigrated)
            )
            case.missing_details = (
                f"{case.missing_details}\n{note}" if case.missing_details else note
            )
            case.save(update_fields=["missing_details"])
    Reference.objects.using(db).bulk_create(rows, batch_size=1000)


def _copy_join_to_court_cases(apps, schema_editor):
    """Reverse: rebuild the JSON list ("<court>:<CASE-NUMBER>") from the join."""
    db = schema_editor.connection.alias
    Case = apps.get_model("cases", "Case")
    Reference = apps.get_model("cases", "CaseCourtCaseReference")
    if not router.allow_migrate_model(db, Reference):
        return
    for case in Case.objects.using(db).iterator():
        refs = []
        for row in (
            Reference.objects.using(db)
            .filter(case=case)
            .order_by("ordinal", "created_at")
        ):
            parsed = parse_courtcase_iri(row.courtcase_iri)
            # Legacy short form kept the source casing (e.g. 080-CR-0111).
            refs.append(f"{parsed.court}:{parsed.case_number.upper()}")
        if refs:
            case.court_cases = refs
            case.save(update_fields=["court_cases"])


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0045_statisticssnapshot_is_placeholder'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseCourtCaseReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courtcase_iri', models.CharField(db_index=True, help_text='Canonical court-case @id IRI (https://jawafdehi.org/courtcase/<court>/<case_number>) this case references. NGM owns the court record; this is the join key only.', max_length=300, validators=[cases.validators.validate_courtcase_iri])),
                ('ordinal', models.PositiveIntegerField(default=0, help_text='Display order of this court-case reference within the case.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this court-case reference was created')),
                ('case', models.ForeignKey(help_text='The case this court-case reference belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='courtcase_references', to='cases.case')),
            ],
            options={
                'verbose_name': 'Case Court Case Reference',
                'verbose_name_plural': 'Case Court Case References',
                'ordering': ['ordinal', 'created_at'],
                'indexes': [models.Index(fields=['case', 'ordinal'], name='case_courtcase_ordinal_idx')],
                'constraints': [models.UniqueConstraint(fields=('case', 'courtcase_iri'), name='unique_case_courtcase_reference')],
            },
        ),
        migrations.RunPython(
            _copy_court_cases_to_join,
            reverse_code=_copy_join_to_court_cases,
        ),
        migrations.RemoveField(
            model_name='case',
            name='court_cases',
        ),
    ]
