# Generated by Codex for newsletter subscriptions.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0046_remove_case_court_cases_casecourtcasereference"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("subscribed", "Subscribed"),
                            ("unsubscribed", "Unsubscribed"),
                        ],
                        db_index=True,
                        default="subscribed",
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-subscribed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="newslettersubscription",
            index=models.Index(
                fields=["status", "subscribed_at"],
                name="cases_newsl_status_dc8026_idx",
            ),
        ),
    ]
