# Generated by Django 5.2.15 on 2026-07-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0046_remove_case_court_cases_casecourtcasereference'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseentityrelationship',
            name='outcome',
            field=models.CharField(choices=[('charged', 'Charged / undecided'), ('convicted', 'Convicted'), ('acquitted', 'Acquitted'), ('abated', 'Abated / discontinued')], db_default='charged', db_index=True, default='charged', help_text="Verdict outcome for this entity in this case (default 'charged' = undecided). Distinct from relationship_type (the role); set only from a primary court order.", max_length=20),
        ),
        migrations.AddIndex(
            model_name='caseentityrelationship',
            index=models.Index(fields=['case', 'outcome'], name='case_outcome_idx'),
        ),
    ]
