# Generated by Codex for newsletter consent and unsubscribe metadata.

import uuid

import django.db.models.functions.text
from django.db import migrations, models


def populate_unsubscribe_tokens(apps, schema_editor):
    NewsletterSubscription = apps.get_model("cases", "NewsletterSubscription")
    by_email = {}
    to_update = []
    to_delete_ids = []
    # Read the full set once, then apply bulk writes after the loop: mutating the
    # table while iterating a server-side cursor can skip rows on PostgreSQL, and
    # per-row save()/delete() is O(N) roundtrips.
    for subscription in NewsletterSubscription.objects.order_by("id"):
        normalized_email = subscription.email.strip().lower()
        keeper = by_email.get(normalized_email)
        if keeper is not None:
            # Preserve opt-outs: an "unsubscribed" duplicate always wins so a
            # consolidated keeper never silently drops a recorded opt-out. Only
            # promote to "subscribed" when the keeper has not opted out.
            if subscription.status == "unsubscribed":
                keeper.status = "unsubscribed"
            elif (
                keeper.status != "unsubscribed"
                and subscription.status == "subscribed"
            ):
                keeper.first_name = subscription.first_name
                keeper.last_name = subscription.last_name
                keeper.status = subscription.status
            to_delete_ids.append(subscription.id)
            continue

        subscription.email = normalized_email
        subscription.unsubscribe_token = uuid.uuid4()
        by_email[normalized_email] = subscription
        to_update.append(subscription)

    if to_update:
        NewsletterSubscription.objects.bulk_update(
            to_update,
            ["email", "unsubscribe_token", "first_name", "last_name", "status"],
        )
    if to_delete_ids:
        NewsletterSubscription.objects.filter(id__in=to_delete_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0047_newslettersubscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newslettersubscription",
            name="email",
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AddField(
            model_name="newslettersubscription",
            name="unsubscribe_token",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="newslettersubscription",
            name="consent_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="newslettersubscription",
            name="consented_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newslettersubscription",
            name="consent_source",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="newslettersubscription",
            name="privacy_version",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="newslettersubscription",
            name="locale",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="newslettersubscription",
            name="unsubscribed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(populate_unsubscribe_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="newslettersubscription",
            name="unsubscribe_token",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AddConstraint(
            model_name="newslettersubscription",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="cases_newsletter_email_ci_uniq",
            ),
        ),
    ]
