# Generated by Codex for newsletter consent and unsubscribe metadata.

import uuid

import django.db.models.functions.text
from django.db import migrations, models


def populate_unsubscribe_tokens(apps, schema_editor):
    NewsletterSubscription = apps.get_model("cases", "NewsletterSubscription")
    by_email = {}
    for subscription in NewsletterSubscription.objects.order_by("id").iterator():
        normalized_email = subscription.email.strip().lower()
        keeper = by_email.get(normalized_email)
        if keeper is not None:
            if (
                keeper.status != "subscribed"
                and subscription.status == "subscribed"
            ):
                keeper.first_name = subscription.first_name
                keeper.last_name = subscription.last_name
                keeper.status = subscription.status
                keeper.save(update_fields=["first_name", "last_name", "status"])
            subscription.delete()
            continue

        subscription.email = normalized_email
        subscription.unsubscribe_token = uuid.uuid4()
        subscription.save(update_fields=["email", "unsubscribe_token"])
        by_email[normalized_email] = subscription


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0047_newslettersubscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newslettersubscription",
            name="email",
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AddField(
            model_name="newslettersubscription",
            name="unsubscribe_token",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="newslettersubscription",
            name="consent_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="newslettersubscription",
            name="consented_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newslettersubscription",
            name="consent_source",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="newslettersubscription",
            name="privacy_version",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="newslettersubscription",
            name="locale",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="newslettersubscription",
            name="unsubscribed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(populate_unsubscribe_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="newslettersubscription",
            name="unsubscribe_token",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AddConstraint(
            model_name="newslettersubscription",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="cases_newsletter_email_ci_uniq",
            ),
        ),
    ]
