# Generated by Django 5.2.15 on 2026-07-08 16:18

from django.db import migrations, models


def null_out_non_accused(apps, schema_editor):
    """A verdict outcome is meaningful only for ACCUSED; clear it on every other
    role so the ``outcome_only_on_accused`` CHECK constraint can be added."""
    CaseEntityRelationship = apps.get_model("cases", "CaseEntityRelationship")
    CaseEntityRelationship.objects.exclude(relationship_type="accused").update(
        outcome=None
    )


def restore_neutral_default(apps, schema_editor):
    """Reverse: restore NULLs to the previous neutral 'charged' so the column
    could go back to NOT NULL if this migration is unwound."""
    CaseEntityRelationship = apps.get_model("cases", "CaseEntityRelationship")
    CaseEntityRelationship.objects.filter(outcome__isnull=True).update(
        outcome="charged"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0047_caseentityrelationship_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseentityrelationship',
            name='outcome',
            field=models.CharField(blank=True, choices=[('charged', 'Charged / undecided'), ('convicted', 'Convicted'), ('acquitted', 'Acquitted'), ('abated', 'Abated / discontinued')], db_index=True, help_text="Verdict outcome for this ACCUSED entity (NULL for every other role). 'charged' = formally charged, verdict pending. Distinct from relationship_type (the role); terminal verdicts are set only from a primary court order.", max_length=20, null=True),
        ),
        # Clear verdicts off non-accused rows BEFORE adding the CHECK, else the
        # constraint validation fails on the existing 'charged' non-accused rows.
        migrations.RunPython(null_out_non_accused, restore_neutral_default),
        migrations.AddConstraint(
            model_name='caseentityrelationship',
            constraint=models.CheckConstraint(condition=models.Q(('relationship_type', 'accused'), ('outcome__isnull', True), _connector='OR'), name='outcome_only_on_accused'),
        ),
    ]
