# Generated by Django 5.2.15 on 2026-07-09 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0048_alter_caseentityrelationship_outcome_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseStateChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DRAFT", "Draft"),
                            ("IN_REVIEW", "In Review"),
                            ("PUBLISHED", "Published"),
                            ("CLOSED", "Closed"),
                        ],
                        default="",
                        max_length=64,
                    ),
                ),
                (
                    "to_state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("IN_REVIEW", "In Review"),
                            ("PUBLISHED", "Published"),
                            ("CLOSED", "Closed"),
                        ],
                        max_length=64,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="case_state_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_changes",
                        to="cases.case",
                    ),
                ),
            ],
            options={
                "verbose_name": "Case State Change",
                "verbose_name_plural": "Case State Changes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["case", "-created_at"],
                        name="cases_cases_case_id_077b25_idx",
                    )
                ],
            },
        ),
    ]
