# Generated by Codex for SendPulse newsletter sync metadata.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0048_newsletter_consent_unsubscribe"),
    ]

    operations = [
        migrations.AddField(
            model_name="newslettersubscription",
            name="sendpulse_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newslettersubscription",
            name="sendpulse_sync_status",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="newslettersubscription",
            name="sendpulse_sync_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="newslettersubscription",
            name="sendpulse_last_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
