# Generated by Django 5.2.15 on 2026-07-08 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0047_caseentityrelationship_outcome'),
        ('cases', '0049_newsletter_sendpulse_sync'),
    ]

    operations = [
    ]
