# Generated by Django 5.2.15 on 2026-07-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0049_casestatechange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
