# Generated by Django 5.2.15 on 2026-07-14 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0050_authz_v3_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseSlugHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slug_history', to='cases.case')),
            ],
            options={
                'verbose_name': 'Case Slug History',
                'verbose_name_plural': 'Case Slug Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
