# Generated by Django 5.2.15 on 2026-07-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0052_widen_auditlog_object_pk"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="public_notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Public notes shown on the case page (markdown): attribution byline plus the human-written 'first published / last edited' line. Editable by casework staff; independent of the internal account that published and of the automatic timestamps. Empty = nothing shown.",
            ),
        ),
    ]
