# Generated by Django 5.2.15 on 2026-07-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0053_case_public_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.CharField(choices=[('CORRUPTION', 'Corruption'), ('BRIBERY', 'Bribery'), ('FORGERY', 'Forgery'), ('EMBEZZLEMENT', 'Embezzlement'), ('ABUSE_OF_OFFICE', 'Abuse of Office'), ('MONEY_LAUNDERING', 'Money Laundering'), ('ILLEGAL_PROPERTY', 'Illegal Property'), ('EXAM_RIGGING', 'Exam Rigging'), ('TAX_EVASION', 'Tax Evasion'), ('BANKING_OFFENCE', 'Banking Offence')], help_text='Type of case', max_length=20),
        ),
    ]
