# Generated by Django 5.2.15 on 2026-08-04 17:28
#
# STATE-ONLY: swaps models.URLField -> cases.fields.HttpsURLField on the two
# Case image URLs. HttpsURLField changes only the FORM layer (it pins
# ``assume_scheme="https"`` so Django 5.x stops emitting
# RemovedInDjango60Warning) and inherits deconstruct(), so the column stays the
# same ``varchar(500)``. The generated SQL is a no-op on Postgres; the AlterField
# exists purely to keep migration state in sync with the model.

import cases.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0054_banking_offence_case_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="banner_url",
            field=cases.fields.HttpsURLField(
                blank=True,
                help_text="URL to a large banner image for the case",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="thumbnail_url",
            field=cases.fields.HttpsURLField(
                blank=True,
                help_text="URL to a small thumbnail picture for the case",
                max_length=500,
            ),
        ),
    ]
