# Generated by Django 5.2.15 on 2026-08-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0055_alter_case_banner_url_alter_case_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('bug', 'Bug Report'), ('feature', 'Feature Request'), ('usability', 'Usability Issue'), ('content', 'Content Feedback'), ('general', 'General Feedback'), ('case_report', 'Corruption Case Report')], help_text='Type of feedback', max_length=20),
        ),
    ]
