# Generated by Django 5.2.15 on 2026-08-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0055_alter_case_banner_url_alter_case_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_end_date',
            field=models.DateField(blank=True, help_text='When the case concluded — the deciding hearing date. Leave empty for a case still being heard: a value here renders the case as concluded on the public site', null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_start_date',
            field=models.DateField(blank=True, help_text='When the case began — the court registration date for a case with a court record', null=True),
        ),
    ]
