# Generated by Django 5.2.15 on 2026-08-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0056_feedback_case_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='weight',
            field=models.IntegerField(default=0, help_text="Editorial priority weight — higher values surface first in the homepage 'Featured Cases' section. 0 (the default) means unranked; ties fall back to newest-first."),
        ),
    ]
