# Generated by Django 5.2.15 on 2026-08-16 16:56, then hand-edited to add the
# order-preserving backfill (see backfill_ordinal below).

from django.db import migrations, models


def backfill_ordinal(apps, schema_editor):
    """Freeze each case's CURRENT visible bind order into the new ordinal.

    Ordering was ``-created_at`` (newest bind first), so that is the order the
    public case pages render today. Walk each case's binds in exactly that order
    and number them 0..n-1, so switching Meta.ordering to ``ordinal`` is a no-op
    for every existing case rather than silently flipping every accused list.

    ``pk`` is the secondary key here for the same reason it is in Meta.ordering:
    bulk-imported binds share a created_at, and without a tie-break the backfill
    would itself pick an arbitrary order.
    """
    CaseEntityRelationship = apps.get_model("cases", "CaseEntityRelationship")

    case_ids = (
        CaseEntityRelationship.objects.order_by()
        .values_list("case_id", flat=True)
        .distinct()
    )
    for case_id in case_ids:
        rels = (
            CaseEntityRelationship.objects.filter(case_id=case_id)
            .order_by("-created_at", "pk")
            .only("pk")
        )
        updates = []
        for ordinal, rel in enumerate(rels):
            rel.ordinal = ordinal
            updates.append(rel)
        if updates:
            CaseEntityRelationship.objects.bulk_update(updates, ["ordinal"])


def noop_reverse(apps, schema_editor):
    """Nothing to undo — the column is dropped by the reverse of AddField."""


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0057_case_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="caseentityrelationship",
            name="ordinal",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Display order of this entity bind within the case.",
            ),
        ),
        # Backfill BEFORE the ordering switch so no read ever sees the new
        # ordering against an all-zero ordinal column.
        migrations.RunPython(backfill_ordinal, noop_reverse),
        migrations.AlterModelOptions(
            name="caseentityrelationship",
            options={
                "ordering": ["ordinal", "created_at", "pk"],
                "verbose_name": "Case Entity Relationship",
                "verbose_name_plural": "Case Entity Relationships",
            },
        ),
        migrations.AddIndex(
            model_name="caseentityrelationship",
            index=models.Index(fields=["case", "ordinal"], name="case_entity_ordinal_idx"),
        ),
    ]
