# Generated by Django 5.2.15 on 2026-08-16 17:39

import cases.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0058_caseentityrelationship_ordinal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_publish_date',
            field=models.DateField(blank=True, help_text='Date this case was first published on jawafdehi.org (AD). Set by casework staff and required before the case can leave DRAFT.', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='public_edit_history',
            field=cases.fields.EditHistoryListField(blank=True, default=list, help_text="Public edit history shown on the case page: a list of {date, remarks} entries, newest handling at the caseworker's discretion. Empty = nothing rendered."),
        ),
        migrations.AlterField(
            model_name='case',
            name='public_notes',
            field=models.TextField(blank=True, default='', help_text='DEPRECATED (superseded by authors / case_publish_date / public_edit_history): free-text public byline, still rendered as a fallback on cases that have no structured authors yet.'),
        ),
        migrations.CreateModel(
            name='CaseAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', help_text="Public byline name, snapshotted from the user at write time so a later rename cannot rewrite a published case's byline.", max_length=150)),
                ('credit_note', models.CharField(blank=True, default='', help_text="Optional per-case qualifier shown after the name, e.g. 'BALLB 4th Year Student'. Per-case, not per-user: the same person may be credited differently on cases written years apart.", max_length=120)),
                ('ordinal', models.PositiveIntegerField(default=0, help_text='Display order of this author within the case byline.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this author credit was created')),
                ('case', models.ForeignKey(help_text='The case this author credit belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='author_credits', to='cases.case')),
                ('user', models.ForeignKey(help_text='The Django account credited as an author of this case', on_delete=django.db.models.deletion.PROTECT, related_name='case_authorships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case Author',
                'verbose_name_plural': 'Case Authors',
                'ordering': ['ordinal', 'created_at'],
                'indexes': [models.Index(fields=['case', 'ordinal'], name='case_author_ordinal_idx')],
                'constraints': [models.UniqueConstraint(fields=('case', 'user'), name='unique_case_author')],
            },
        ),
    ]
