# Generated by Django 5.2.15 on 2026-08-16 18:56

import cases.fields
import cases.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_profiles_for_existing_credits(apps, schema_editor):
    """Give every already-credited account a profile, and therefore a slug.

    ``CaseAuthor.save()`` does this going forward, but rows written before this
    migration (and any written by bulk paths that bypass save()) would otherwise
    have no profile and no slug, which is exactly the invariant the author page
    relies on.

    Slugs are minted here rather than by calling ``AuthorProfile.ensure_for``:
    historical models carry no custom methods, so the logic is duplicated
    deliberately and kept simple.
    """
    from django.utils.text import slugify

    AuthorProfile = apps.get_model("cases", "AuthorProfile")
    CaseAuthor = apps.get_model("cases", "CaseAuthor")

    taken = set(AuthorProfile.objects.values_list("slug", flat=True))
    user_ids = CaseAuthor.objects.values_list("user_id", flat=True).distinct()
    for user_id in user_ids:
        if AuthorProfile.objects.filter(user_id=user_id).exists():
            continue
        user = CaseAuthor.objects.filter(user_id=user_id).first().user
        name = (f"{user.first_name} {user.last_name}".strip()) or user.username
        base = slugify(name) or "author"
        if not base[0].isalpha():
            base = f"author-{base}"
        base = base[:55].strip("-") or "author"
        candidate, suffix = base, 1
        while candidate in taken:
            suffix += 1
            tail = f"-{suffix}"
            candidate = f"{base[: 60 - len(tail)]}{tail}"
        taken.add(candidate)
        AuthorProfile.objects.create(user_id=user_id, slug=candidate, name_en=name)


def drop_generated_profiles(apps, schema_editor):
    """No-op reverse: the table is dropped by the CreateModel rollback anyway."""


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0059_case_authors_and_publish_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="caseauthor",
            name="credit_note",
        ),
        migrations.RemoveField(
            model_name="caseauthor",
            name="display_name",
        ),
        migrations.AddField(
            model_name="case",
            name="authors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Credited authors of this case, ordered by CaseAuthor.ordinal",
                related_name="authored_cases",
                through="cases.CaseAuthor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="AuthorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL handle for the public profile (jawafdehi.org/author/<slug>). Generated from the name on first credit and stable thereafter.",
                        max_length=60,
                        unique=True,
                        validators=[cases.validators.validate_slug],
                    ),
                ),
                ("name_en", models.CharField(blank=True, default="", max_length=150)),
                ("name_ne", models.CharField(blank=True, default="", max_length=150)),
                (
                    "photo_url",
                    cases.fields.HttpsURLField(
                        blank=True,
                        help_text="Profile picture URL (hosted; the team photos live on R2)",
                        max_length=500,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Short public bio shown on the author card and profile page, e.g. 'Caseworker' or 'BALLB 4th Year Student'.",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Public contact address. Blank = not shown anywhere.",
                        max_length=254,
                    ),
                ),
                (
                    "links",
                    cases.fields.AuthorLinkListField(
                        blank=True,
                        default=list,
                        help_text="Public social links: [{type, value}] with https:// URLs.",
                    ),
                ),
                (
                    "has_public_page",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether /author/<slug> is published and author cards link to it. Off by default: a profile is created automatically on first credit and starts empty, and an empty public page is worse than none.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The account this profile describes",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Author Profile",
                "verbose_name_plural": "Author Profiles",
                "ordering": ["name_en", "slug"],
            },
        ),
        migrations.RunPython(
            create_profiles_for_existing_credits,
            drop_generated_profiles,
        ),
    ]
