# Generated by Django 5.2.15 on 2026-09-02 03:19

import cases.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0061_author_title_and_bio'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='banner_image',
            field=models.ForeignKey(blank=True, help_text='Hero image, shown at the top of the case detail page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='case',
            name='thumbnail_image',
            field=models.ForeignKey(blank=True, help_text='Card image, shown on the home page and in search results', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='case',
            name='banner_url',
            field=cases.fields.HttpsURLField(blank=True, help_text='DEPRECATED. External URL for the hero image; use banner_image', max_length=500),
        ),
        migrations.AlterField(
            model_name='case',
            name='thumbnail_url',
            field=cases.fields.HttpsURLField(blank=True, help_text='DEPRECATED. External URL for the card image; use thumbnail_image', max_length=500),
        ),
    ]
