# Generated by Django 5.2.15 on 2026-08-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0061_author_title_and_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='tags_source',
            field=models.JSONField(blank=True, editable=False, help_text='Pre-canonicalisation snapshot of tags. Audit trail, not public.', null=True),
        ),
    ]
