# Generated by Django 5.2.15 on 2026-09-10 12:15

from django.db import migrations, models

# Help text only -- no column, index or constraint changes, so this is a
# metadata-only AlterField and applies instantly on any table size. It exists
# because the old text ("When the alleged incident began") was wrong and
# load-bearing: it is what the admin form shows caseworkers and what OpenAPI
# publishes. Both columns hold COURT dates and always did.


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0068_populate_case_stages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_end_date',
            field=models.DateField(blank=True, help_text="DEPRECATED — edit the stage list instead. The first-instance court decision date, served as an alias off the single 'initial' stage.", null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_start_date',
            field=models.DateField(blank=True, help_text="DEPRECATED — edit the stage list instead. The first-instance court registration date, served as an alias off the single 'initial' stage.", null=True),
        ),
    ]
