# Generated by Django 5.2.15 on 2026-10-07 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0069_correct_legacy_date_help_text"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OIDCIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        db_index=True,
                        help_text="The OIDC `sub` claim — Zitadel's immutable user id.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this subject was first bound to the user.",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The Django user this subject resolves to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oidc_identity",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OIDC Identity",
                "verbose_name_plural": "OIDC Identities",
            },
        ),
    ]
