# Generated by Django 5.2.15 on 2026-06-28 05:42

import materials.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="iri",
            field=models.CharField(
                max_length=300,
                primary_key=True,
                serialize=False,
                validators=[materials.models.validate_material_iri],
            ),
        ),
    ]
