# Generated by Django 5.2.15 on 2026-07-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_alter_material_iri"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
