# Generated by Django 5.2.15 on 2026-07-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_material_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("LISTED", "Listed"),
                    ("UNLISTED", "Unlisted"),
                    ("PRIVATE", "Private"),
                ],
                db_index=True,
                default="LISTED",
                max_length=10,
            ),
        ),
    ]
