# Generated by Django 5.2.15 on 2026-10-07 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_material_visibility_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentExtraction',
            fields=[
                ('material', models.OneToOneField(db_column='material_iri', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extraction', serialize=False, to='materials.material')),
                ('doc_id', models.CharField(db_index=True, max_length=120)),
                ('dataset', models.CharField(max_length=200)),
                ('dataset_revision', models.CharField(blank=True, max_length=80)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('text_source', models.CharField(blank=True, max_length=40)),
                ('transcript_verdict', models.CharField(blank=True, max_length=40)),
                ('figures_verdict', models.CharField(blank=True, max_length=40)),
                ('ingested_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'material_document_extractions',
            },
        ),
        migrations.CreateModel(
            name='ExtractedFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('key', models.CharField(max_length=40)),
                ('uid', models.CharField(max_length=160)),
                ('page_no', models.PositiveIntegerField()),
                ('index_on_page', models.PositiveSmallIntegerField(default=1)),
                ('title', models.TextField(blank=True)),
                ('chart_type', models.CharField(blank=True, max_length=40)),
                ('unit', models.CharField(blank=True, max_length=80)),
                ('x_axis', models.CharField(blank=True, max_length=300)),
                ('y_axis', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('verify_note', models.TextField(blank=True)),
                ('verified', models.BooleanField(blank=True, null=True)),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figures', to='materials.documentextraction')),
            ],
            options={
                'db_table': 'material_extracted_figures',
                'ordering': ('ordinal',),
            },
        ),
        migrations.CreateModel(
            name='ExtractedFigurePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_index', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, max_length=300)),
                ('series', models.CharField(blank=True, max_length=300)),
                ('value', models.FloatField(blank=True, null=True)),
                ('is_estimated', models.BooleanField(default=False)),
                ('figure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='materials.extractedfigure')),
            ],
            options={
                'db_table': 'material_extracted_figure_points',
                'ordering': ('point_index', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ExtractedTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('key', models.CharField(max_length=40)),
                ('uid', models.CharField(max_length=160)),
                ('page_no', models.PositiveIntegerField()),
                ('index_on_page', models.PositiveSmallIntegerField(default=1)),
                ('caption', models.TextField(blank=True)),
                ('header', models.JSONField(blank=True, default=list)),
                ('n_rows', models.PositiveIntegerField(default=0)),
                ('n_cols', models.PositiveIntegerField(default=0)),
                ('fidelity', models.CharField(blank=True, max_length=40)),
                ('markdown', models.TextField()),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='materials.documentextraction')),
            ],
            options={
                'db_table': 'material_extracted_tables',
                'ordering': ('ordinal',),
            },
        ),
        migrations.AddConstraint(
            model_name='extractedfigure',
            constraint=models.UniqueConstraint(fields=('extraction', 'ordinal'), name='uniq_extracted_figure_ordinal'),
        ),
        migrations.AddConstraint(
            model_name='extractedfigure',
            constraint=models.UniqueConstraint(fields=('extraction', 'key'), name='uniq_extracted_figure_key'),
        ),
        migrations.AddConstraint(
            model_name='extractedfigure',
            constraint=models.UniqueConstraint(fields=('extraction', 'uid'), name='uniq_extracted_figure_uid'),
        ),
        migrations.AddConstraint(
            model_name='extractedfigurepoint',
            constraint=models.UniqueConstraint(fields=('figure', 'point_index'), name='uniq_figure_point_index'),
        ),
        migrations.AddConstraint(
            model_name='extractedtable',
            constraint=models.UniqueConstraint(fields=('extraction', 'ordinal'), name='uniq_extracted_table_ordinal'),
        ),
        migrations.AddConstraint(
            model_name='extractedtable',
            constraint=models.UniqueConstraint(fields=('extraction', 'key'), name='uniq_extracted_table_key'),
        ),
        migrations.AddConstraint(
            model_name='extractedtable',
            constraint=models.UniqueConstraint(fields=('extraction', 'uid'), name='uniq_extracted_table_uid'),
        ),
    ]
