# Generated by Lemon for JAWA-2050

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NesEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        help_text="Full computed entity ID, e.g. 'entity:person/nepal_govt/john-doe'.",
                        max_length=512,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        help_text="URL-friendly identifier for the entity.",
                        max_length=100,
                    ),
                ),
                (
                    "entity_prefix",
                    models.CharField(
                        help_text="Slash-joined classification prefix, e.g. 'person/nepal_govt'.",
                        max_length=512,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        help_text="Tags as a list of strings.",
                        null=True,
                    ),
                ),
                (
                    "version_summary",
                    models.JSONField(
                        help_text="Latest version summary (VersionSummary as dict).",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        help_text="Timestamp from the NES entity record.",
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(
                        help_text="Full NES entity JSON as stored in nes-db.",
                    ),
                ),
                (
                    "last_modified_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this row was last modified in Postgres.",
                    ),
                ),
            ],
            options={
                "verbose_name": "NES Entity",
                "verbose_name_plural": "NES Entities",
                "ordering": ["entity_id"],
                "indexes": [
                    models.Index(
                        fields=["entity_prefix"],
                        name="nesdb_entity_prefix_idx",
                    ),
                    models.Index(
                        fields=["slug"],
                        name="nesdb_entity_slug_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NesEntityName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("PRIMARY", "Primary"),
                            ("ALIAS", "Alias"),
                            ("ALTERNATE", "Alternate"),
                            ("BIRTH_NAME", "Birth Name"),
                        ],
                        help_text="Type of name.",
                        max_length=20,
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        help_text="Concatenated English/romanised name.",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "name_ne",
                    models.CharField(
                        blank=True,
                        help_text="Concatenated Nepali (Devanagari) name.",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        db_index=False,
                        help_text="The entity this name belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="names",
                        to="nesdb.nesentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "NES Entity Name",
                "verbose_name_plural": "NES Entity Names",
                "ordering": ["entity", "pk"],
                "indexes": [
                    models.Index(
                        fields=["entity", "kind"],
                        name="nesdb_name_entity_kind_idx",
                    ),
                    models.Index(
                        condition=models.Q(("name_en__isnull", False)),
                        fields=["name_en"],
                        name="nesdb_name_en_idx",
                    ),
                    models.Index(
                        condition=models.Q(("name_ne__isnull", False)),
                        fields=["name_ne"],
                        name="nesdb_name_ne_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NesRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_id",
                    models.CharField(
                        help_text="Full computed relationship ID.",
                        max_length=1024,
                        unique=True,
                    ),
                ),
                (
                    "source_entity_id",
                    models.CharField(
                        help_text="Entity ID of the relationship source.",
                        max_length=512,
                    ),
                ),
                (
                    "target_entity_id",
                    models.CharField(
                        help_text="Entity ID of the relationship target.",
                        max_length=512,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        help_text="Relationship type, e.g. 'EMPLOYED_BY', 'MEMBER_OF'.",
                        max_length=64,
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(
                        help_text="Full NES relationship JSON as stored in nes-db.",
                    ),
                ),
                ("last_modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "NES Relationship",
                "verbose_name_plural": "NES Relationships",
                "ordering": ["relationship_id"],
                "indexes": [
                    models.Index(
                        fields=["source_entity_id"],
                        name="nesdb_rel_source_idx",
                    ),
                    models.Index(
                        fields=["target_entity_id"],
                        name="nesdb_rel_target_idx",
                    ),
                    models.Index(
                        fields=["type"],
                        name="nesdb_rel_type_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NesSyncState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_commit_hash",
                    models.CharField(
                        help_text="SHA of the last synced commit in the nes-db repository.",
                        max_length=64,
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of the most recent successful sync.",
                    ),
                ),
                ("entities_upserted", models.IntegerField(default=0)),
                ("entities_deleted", models.IntegerField(default=0)),
                ("relationships_upserted", models.IntegerField(default=0)),
                ("relationships_deleted", models.IntegerField(default=0)),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error details if the last sync failed.",
                    ),
                ),
            ],
            options={
                "verbose_name": "NES Sync State",
                "verbose_name_plural": "NES Sync States",
            },
        ),
    ]
