# Generated by Django 5.2.9 on 2026-05-31 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NesSyncState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_commit_hash",
                    models.CharField(
                        help_text="SHA of the last synced commit in the nes-db repository.",
                        max_length=40,
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of the most recent successful sync.",
                    ),
                ),
                ("entities_upserted", models.IntegerField(default=0)),
                ("entities_deleted", models.IntegerField(default=0)),
                ("relationships_upserted", models.IntegerField(default=0)),
                ("relationships_deleted", models.IntegerField(default=0)),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error details if the last sync failed.",
                    ),
                ),
            ],
            options={
                "verbose_name": "NES Sync State",
                "verbose_name_plural": "NES Sync States",
            },
        ),
        migrations.CreateModel(
            name="NesEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        db_index=True,
                        help_text="Full computed entity ID, e.g. 'entity:person/nepal_govt/john-doe'.",
                        max_length=512,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        help_text="URL-friendly identifier for the entity.",
                        max_length=100,
                    ),
                ),
                (
                    "entity_prefix",
                    models.CharField(
                        db_index=True,
                        help_text="Slash-joined classification prefix, e.g. 'person/nepal_govt'.",
                        max_length=512,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        help_text="Entity type: person, organization, location, or project.",
                        max_length=32,
                    ),
                ),
                (
                    "sub_type",
                    models.CharField(
                        blank=True,
                        help_text="Entity subtype (deprecated in NES, use entity_prefix).",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "version_summary",
                    models.JSONField(
                        help_text="Latest version summary (VersionSummary as dict)."
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        help_text="Timestamp from the NES entity record."
                    ),
                ),
                (
                    "identifiers",
                    models.JSONField(
                        blank=True,
                        help_text="External identifiers (list of dicts).",
                        null=True,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, help_text="Tags as a list of strings.", null=True
                    ),
                ),
                (
                    "attributes",
                    models.JSONField(
                        blank=True,
                        help_text="Additional free-form attributes.",
                        null=True,
                    ),
                ),
                (
                    "contacts",
                    models.JSONField(
                        blank=True,
                        help_text="Contact information (list of dicts).",
                        null=True,
                    ),
                ),
                (
                    "short_description",
                    models.JSONField(
                        blank=True,
                        help_text="Brief description as LangText dict.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.JSONField(
                        blank=True,
                        help_text="Detailed description as LangText dict.",
                        null=True,
                    ),
                ),
                (
                    "attributions",
                    models.JSONField(
                        blank=True,
                        help_text="Source attributions (list of dicts).",
                        null=True,
                    ),
                ),
                (
                    "pictures",
                    models.JSONField(
                        blank=True,
                        help_text="Entity pictures (list of dicts).",
                        null=True,
                    ),
                ),
                (
                    "last_modified_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this row was last modified in Postgres.",
                    ),
                ),
            ],
            options={
                "verbose_name": "NES Entity",
                "verbose_name_plural": "NES Entities",
                "ordering": ["entity_id"],
                "indexes": [
                    models.Index(fields=["type"], name="nesdb_entity_type_idx"),
                    models.Index(
                        fields=["entity_prefix"], name="nesdb_entity_prefix_idx"
                    ),
                    models.Index(fields=["slug"], name="nesdb_entity_slug_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="NesRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_id",
                    models.CharField(
                        db_index=True,
                        help_text="Full computed relationship ID.",
                        max_length=1024,
                        unique=True,
                    ),
                ),
                (
                    "source_entity_id",
                    models.CharField(
                        db_index=True,
                        help_text="Entity ID of the relationship source.",
                        max_length=512,
                    ),
                ),
                (
                    "target_entity_id",
                    models.CharField(
                        db_index=True,
                        help_text="Entity ID of the relationship target.",
                        max_length=512,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        help_text="Relationship type, e.g. 'EMPLOYED_BY', 'MEMBER_OF'.",
                        max_length=64,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("attributes", models.JSONField(blank=True, null=True)),
                ("version_summary", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("attributions", models.JSONField(blank=True, null=True)),
                ("last_modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "NES Relationship",
                "verbose_name_plural": "NES Relationships",
                "ordering": ["relationship_id"],
                "indexes": [
                    models.Index(
                        fields=["source_entity_id"], name="nesdb_rel_source_idx"
                    ),
                    models.Index(
                        fields=["target_entity_id"], name="nesdb_rel_target_idx"
                    ),
                    models.Index(fields=["type"], name="nesdb_rel_type_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="NesEntityName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("PRIMARY", "Primary"),
                            ("ALIAS", "Alias"),
                            ("ALTERNATE", "Alternate"),
                            ("BIRTH_NAME", "Birth Name"),
                        ],
                        help_text="Type of name.",
                        max_length=20,
                    ),
                ),
                (
                    "en_full",
                    models.CharField(
                        blank=True,
                        help_text="English/romanised full name.",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "en_given",
                    models.CharField(
                        blank=True,
                        help_text="English given name.",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "en_middle",
                    models.CharField(
                        blank=True,
                        help_text="English middle name.",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "en_family",
                    models.CharField(
                        blank=True,
                        help_text="English family name.",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "en_prefix",
                    models.CharField(
                        blank=True,
                        help_text="English name prefix.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "en_suffix",
                    models.CharField(
                        blank=True,
                        help_text="English name suffix.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "ne_full",
                    models.CharField(
                        blank=True,
                        help_text="Nepali (Devanagari) full name.",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "ne_given",
                    models.CharField(
                        blank=True,
                        help_text="Nepali given name.",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "ne_middle",
                    models.CharField(
                        blank=True,
                        help_text="Nepali middle name.",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "ne_family",
                    models.CharField(
                        blank=True,
                        help_text="Nepali family name.",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "ne_prefix",
                    models.CharField(
                        blank=True,
                        help_text="Nepali name prefix.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "ne_suffix",
                    models.CharField(
                        blank=True,
                        help_text="Nepali name suffix.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        help_text="The entity this name belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="names",
                        to="nesdb.nesentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "NES Entity Name",
                "verbose_name_plural": "NES Entity Names",
                "ordering": ["entity", "pk"],
                "indexes": [
                    models.Index(
                        fields=["entity", "kind"], name="nesdb_name_entity_kind_idx"
                    )
                ],
            },
        ),
    ]
