# Generated by Codex on 2026-05-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caseworker", "0007_encrypt_llm_provider_api_keys"),
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RAGSkillProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.SlugField(max_length=120, unique=True)),
                ("display_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "trigger_keywords",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text=(
                            "Case-insensitive phrases that trigger this RAG skill."
                        ),
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=100,
                        help_text=(
                            "Lower values match first when multiple RAG skills trigger."
                        ),
                    ),
                ),
                ("max_results", models.PositiveIntegerField(default=5)),
                ("min_keyword_matches", models.PositiveIntegerField(default=1)),
                ("requires_citations", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("source_path", models.CharField(blank=True, max_length=1000)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "collections",
                    models.ManyToManyField(
                        help_text=(
                            "Knowledge collections searched when this RAG skill "
                            "matches."
                        ),
                        related_name="rag_skill_profiles",
                        to="knowledge.knowledgecollection",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        help_text=(
                            "Prompt instructions loaded from the skill pack SKILL.md."
                        ),
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rag_skill_profiles",
                        to="caseworker.skill",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "name"],
            },
        ),
        migrations.AddField(
            model_name="publicchatconfig",
            name="rag_skill_profiles",
            field=models.ManyToManyField(
                blank=True,
                help_text=(
                    "File-synced RAG skills available to anonymous public chat."
                ),
                related_name="public_chat_configs",
                to="caseworker.ragskillprofile",
            ),
        ),
    ]
