# Generated by Django 5.2.15 on 2026-06-09 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pass_threshold", models.IntegerField(default=80)),
                ("revise_threshold", models.IntegerField(default=60)),
                ("llm_samples", models.IntegerField(default=3)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CaseReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "In progress"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("stage", models.CharField(blank=True, default="", max_length=64)),
                ("error", models.TextField(blank=True, default="")),
                (
                    "case_title",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("case_state", models.CharField(blank=True, default="", max_length=64)),
                ("case_type", models.CharField(blank=True, default="", max_length=32)),
                ("source_count", models.IntegerField(default=0)),
                ("sources_converted", models.IntegerField(default=0)),
                ("result", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=80, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("category", models.CharField(default="General", max_length=80)),
                ("description", models.TextField(blank=True, default="")),
                ("good_examples", models.TextField(blank=True, default="")),
                ("bad_examples", models.TextField(blank=True, default="")),
                (
                    "condition_text",
                    models.CharField(blank=True, default="", max_length=400),
                ),
                ("applies_to", models.JSONField(default=list)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("deterministic", "Deterministic"),
                            ("llm", "LLM judge"),
                        ],
                        default="deterministic",
                        max_length=16,
                    ),
                ),
                ("detector", models.CharField(blank=True, default="", max_length=80)),
                ("weight", models.FloatField(default=1.0)),
                ("is_gate", models.BooleanField(default=False)),
                ("gate_min", models.IntegerField(default=50)),
                ("enabled", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
