# Generated by Django 5.2.9 on 2026-06-16 04:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0002_delete_rule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="casereview",
            constraint=models.UniqueConstraint(
                condition=models.Q(status__in=["pending", "running"]),
                fields=("slug",),
                name="uniq_active_review_per_case",
            ),
        ),
    ]
