# Generated by Django 5.2.15 on 2026-07-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_delete_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casereview',
            name='slug',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
