"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from datetime import timedelta
from pathlib import Path

import dj_database_url
import sentry_sdk
import structlog as _structlog
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
from sentry_sdk.integrations.django import DjangoIntegration

from config.structlog_config import configure_structlog

load_dotenv()

configure_structlog()

_sentry_dsn = os.getenv("SENTRY_DSN")
if _sentry_dsn:
    sentry_sdk.init(
        dsn=_sentry_dsn,
        integrations=[
            DjangoIntegration(),
        ],
        traces_sample_rate=float(os.getenv("SENTRY_TRACES_SAMPLE_RATE", "1.0")),
        send_default_pii=False,
        environment=os.getenv("SENTRY_ENVIRONMENT", "production"),
    )


def get_env_list(name, default=""):
    value = os.getenv(name, default)
    return [item.strip() for item in value.split(",") if item.strip()]


def env_flag(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default

    normalized = value.strip().lower()
    if normalized in {"true", "1", "yes", "y", "on"}:
        return True
    if normalized in {"false", "0", "no", "n", "off"}:
        return False
    return default


def ensure_trailing_slash(value):
    if not value:
        return value
    return value if value.endswith("/") else f"{value}/"


def build_s3_storage_options(
    access_key,
    secret_key,
    bucket_name,
    region_name,
    endpoint_url,
    use_ssl,
    custom_domain=None,
):
    storage_options = {
        "access_key": access_key,
        "secret_key": secret_key,
        "bucket_name": bucket_name,
        "region_name": region_name,
        "endpoint_url": endpoint_url,
        "use_ssl": use_ssl,
        "querystring_auth": False,
    }

    if custom_domain:
        storage_options["custom_domain"] = custom_domain

    return storage_options


def build_media_url(
    explicit_media_url=None,
    custom_domain=None,
    endpoint_url=None,
    bucket_name=None,
    use_ssl=True,
):
    if explicit_media_url:
        return ensure_trailing_slash(explicit_media_url)

    if custom_domain:
        if custom_domain.startswith(("http://", "https://")):
            return ensure_trailing_slash(custom_domain)
        scheme = "https" if use_ssl else "http"
        return f"{scheme}://{ensure_trailing_slash(custom_domain)}"

    if endpoint_url and bucket_name:
        return f"{ensure_trailing_slash(endpoint_url)}{bucket_name}/"

    return "/media/"


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY or SECRET_KEY.startswith("django-insecure-"):
    raise ImproperlyConfigured(
        "SECRET_KEY environment variable must be set to a secure value. "
        "Generate one with: python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'"
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = get_env_list("ALLOWED_HOSTS", "")
if not DEBUG and not ALLOWED_HOSTS:
    raise ImproperlyConfigured(
        "ALLOWED_HOSTS environment variable must be set in production. "
        "Set it to a comma-separated list of allowed hostnames "
        "(e.g. ALLOWED_HOSTS=jawafdehi.org,beta.jawafdehi.org)."
    )

CSRF_TRUSTED_ORIGINS = get_env_list("CSRF_TRUSTED_ORIGINS")


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {
            "()": _structlog.stdlib.ProcessorFormatter,
            "processor": _structlog.processors.JSONRenderer(),
            "foreign_pre_chain": [
                _structlog.contextvars.merge_contextvars,
                _structlog.processors.TimeStamper(fmt="iso", utc=True),
                _structlog.stdlib.add_logger_name,
                _structlog.stdlib.add_log_level,
                _structlog.stdlib.ExtraAdder(),
            ],
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "json",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.server": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": os.getenv("ROOT_LOG_LEVEL", "INFO"),
    },
}


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "django_filters",
    "corsheaders",
    "auditlog",
    "rules.apps.AutodiscoverRulesConfig",
    "cases",
    "nesq",
    "ngm",
    "caseworker",
    "case_workflows",
    # Casework Review System (VOL-3): rule-centered case-quality review.
    "review",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "config.middleware.RequestIdMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "auditlog.middleware.AuditlogMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Where a successful session login redirects when no ?next= is supplied.
# The only session-login surface here is the Django admin (the casework portal
# uses JWT and never touches this), so send admin logins to the admin index
# instead of Django's nonexistent default of /accounts/profile/.
LOGIN_REDIRECT_URL = "/admin/"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# SSL-related PostgreSQL connection parameters that dj_database_url may place
# at the top level of the config dict when they appear as URL query params
# (e.g. ?sslmode=verify-ca&sslrootcert=/path/to/ca.pem). These need to be
# moved into OPTIONS for Django / psycopg2 to interpret them correctly.
_SSL_PARAMS = frozenset(
    {
        "sslmode",
        "sslrootcert",
        "sslcert",
        "sslkey",
        "sslcrl",
        "sslpassword",
        "sslcompression",
        "sslsni",
    }
)


def _apply_db_ssl_options(db_config):
    """Apply SSL options to a PostgreSQL database config.

    Sources (in priority order — first wins):
    1. URL query parameters already in the config dict
       (dj_database_url places them at the top level)
    2. Environment variables:
       - DATABASE_SSL_MODE            → sslmode
       - DATABASE_SSL_CA_CERT_FILE    → sslrootcert
       - DATABASE_SSL_CLIENT_CERT_FILE → sslcert
       - DATABASE_SSL_CLIENT_KEY_FILE  → sslkey

    If the engine is not PostgreSQL this is a no-op.
    """
    if db_config.get("ENGINE") != "django.db.backends.postgresql":
        return db_config

    options = db_config.setdefault("OPTIONS", {})

    # Move SSL params that came in via URL query string into OPTIONS.
    for param in _SSL_PARAMS:
        if param in db_config:
            options.setdefault(param, db_config.pop(param))

    # Apply from environment variables (won't override URL-provided values).
    ssl_mode = os.getenv("DATABASE_SSL_MODE")
    if ssl_mode:
        options.setdefault("sslmode", ssl_mode)

    ca_cert = os.getenv("DATABASE_SSL_CA_CERT_FILE") or os.getenv("SSL_CA_CERT_FILE")
    if ca_cert:
        options.setdefault("sslrootcert", ca_cert)

    client_cert = os.getenv("DATABASE_SSL_CLIENT_CERT_FILE") or os.getenv(
        "SSL_CLIENT_CERT_FILE"
    )
    if client_cert:
        options.setdefault("sslcert", client_cert)

    client_key = os.getenv("DATABASE_SSL_CLIENT_KEY_FILE") or os.getenv(
        "SSL_CLIENT_KEY_FILE"
    )
    if client_key:
        options.setdefault("sslkey", client_key)

    return db_config


# Handle secret interpolation for database URLs
def interpolate_db_url(url_env_name):
    url = os.getenv(url_env_name)
    if not url:
        return
    password = os.getenv("DATABASE_PASSWORD")
    if password:
        url = url.replace("${DATABASE_PASSWORD}", password)
        os.environ[url_env_name] = url


interpolate_db_url("DATABASE_URL")
interpolate_db_url("NGM_DATABASE_URL")

DATABASES = {
    "default": dj_database_url.config(
        default="sqlite:///db.sqlite3",
    )
}

# Dynamic interpolation of database password from environment variable
# This allows us to inject the password from Google Secret Manager at runtime
db_password = os.getenv("DATABASE_PASSWORD")
if db_password:
    for db_key in DATABASES:
        db_url = os.getenv(f"{db_key.upper()}_DATABASE_URL") or os.getenv(
            "DATABASE_URL"
        )
        if db_url and "${DATABASE_PASSWORD}" in db_url:
            DATABASES[db_key]["PASSWORD"] = db_password
            new_url = db_url.replace("${DATABASE_PASSWORD}", db_password)
            DATABASES[db_key] = dj_database_url.parse(new_url)

if os.getenv("NGM_DATABASE_URL"):
    DATABASES["ngm"] = dj_database_url.config(env="NGM_DATABASE_URL")
    if db_password and "${DATABASE_PASSWORD}" in os.getenv("NGM_DATABASE_URL"):
        new_url = os.getenv("NGM_DATABASE_URL").replace(
            "${DATABASE_PASSWORD}", db_password
        )
        DATABASES["ngm"] = dj_database_url.parse(new_url)

# Apply SSL options to all PostgreSQL databases.
# Must run after password interpolation so that re-parsed configs also
# receive SSL options.
for db_key in DATABASES:
    _apply_db_ssl_options(DATABASES[db_key])

# Configure connection pooling for PostgreSQL only
if DATABASES["default"].get("ENGINE") == "django.db.backends.postgresql":
    DATABASES["default"]["CONN_MAX_AGE"] = 60
    DATABASES["default"]["CONN_HEALTH_CHECKS"] = True

if (
    "ngm" in DATABASES
    and DATABASES["ngm"].get("ENGINE") == "django.db.backends.postgresql"
):
    DATABASES["ngm"]["CONN_MAX_AGE"] = 60
    DATABASES["ngm"]["CONN_HEALTH_CHECKS"] = True


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Authentication backends
AUTHENTICATION_BACKENDS = [
    "rules.permissions.ObjectPermissionBackend",
    "django.contrib.auth.backends.ModelBackend",
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kathmandu"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Additional locations of static files
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Whitenoise configuration for serving static files
# Configure storage backend - use S3/R2 if AWS credentials are available, otherwise use FileSystemStorage
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME", "jawafdehi")
AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", "auto")
AWS_S3_ENDPOINT_URL = os.getenv("AWS_S3_ENDPOINT_URL")
AWS_S3_CUSTOM_DOMAIN = os.getenv("AWS_S3_CUSTOM_DOMAIN")
AWS_S3_USE_SSL = env_flag("AWS_S3_USE_SSL", True)

if AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY:
    # Use django-storages with S3 backend for both local (Minio) and cloud (R2/AWS S3)
    storage_options = build_s3_storage_options(
        access_key=AWS_ACCESS_KEY_ID,
        secret_key=AWS_SECRET_ACCESS_KEY,
        bucket_name=AWS_STORAGE_BUCKET_NAME,
        region_name=AWS_S3_REGION_NAME,
        endpoint_url=AWS_S3_ENDPOINT_URL,
        use_ssl=AWS_S3_USE_SSL,
        custom_domain=AWS_S3_CUSTOM_DOMAIN,
    )

    STORAGES = {
        "default": {
            "BACKEND": "cases.storage.HashedFilenameS3Boto3Storage",
            "OPTIONS": storage_options,
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
else:
    # Development: use FileSystemStorage
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

# Media Files Configuration
MEDIA_URL = build_media_url(
    explicit_media_url=os.getenv("MEDIA_URL"),
    custom_domain=AWS_S3_CUSTOM_DOMAIN,
    endpoint_url=AWS_S3_ENDPOINT_URL,
    bucket_name=(
        AWS_STORAGE_BUCKET_NAME if AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY else None
    ),
    use_ssl=AWS_S3_USE_SSL,
)
MEDIA_ROOT = os.getenv("MEDIA_ROOT", BASE_DIR / "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Detect test runner to disable throttling during tests (global rate limits
# applied by JAW-60 would cause 429s in the test suite).
TESTING = os.getenv("TESTING") == "true" or any("pytest" in arg for arg in sys.argv)

# REST Framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

if not TESTING:
    REST_FRAMEWORK["DEFAULT_THROTTLE_CLASSES"] = [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ]
    REST_FRAMEWORK["DEFAULT_THROTTLE_RATES"] = {
        "anon": "100/hour",
        "user": "1000/hour",
    }

# JWT Configuration
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=24),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
}


SPECTACULAR_SETTINGS = {
    "TITLE": "Jawafdehi Public Accountability API",
    "DESCRIPTION": """
Public API for the Jawafdehi accountability platform.

This API provides read-only access to published cases of alleged corruption
and misconduct by public entities in Nepal.

## Features

- **Browse Cases**: List all published cases with filtering and search
- **View Details**: Get complete case information including evidence and timeline
- **Audit History**: Access version history for published cases
- **Document Sources**: Browse evidence sources associated with published cases

## Access

All endpoints are public and do not require authentication. Only published
cases (state=PUBLISHED) are accessible through this API.

## Filtering & Search

The cases endpoint supports:
- Filtering by case type and tags
- Full-text search across title, description, and key allegations
- Pagination (20 items per page)
    """,
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": "/api/",
    "SERVERS": None,  # Use None to auto-detect from request
    "TAGS": [
        {"name": "cases", "description": "Operations related to accountability cases"},
        {
            "name": "sources",
            "description": "Operations related to document sources and evidence",
        },
    ],
    "ENUM_NAME_OVERRIDES": {
        "CaseTypeEnum": "cases.models.CaseType",
    },
}

# CORS
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = get_env_list(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:8080,http://127.0.0.1:8080,https://jawafdehi.org,https://beta.jawafdehi.org",
)
# Allow the casework portal SPA served from the project's Cloudflare workers.dev
# domain — newnepal.workers.dev and its per-version preview subdomains
# (e.g. abc123.newnepal.workers.dev) — to call the API (e.g. the JWT token
# endpoint) cross-origin.
CORS_ALLOWED_ORIGIN_REGEXES = get_env_list(
    "CORS_ALLOWED_ORIGIN_REGEXES",
    r"^https://([a-z0-9-]+\.)?newnepal\.workers\.dev$",
)
CORS_ALLOW_METHODS = ["GET", "HEAD", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]
CORS_ALLOW_CREDENTIALS = True

# Keep Django's CSRF origin validation aligned with credentialed CORS writes.
if not CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS.copy()

# Security headers and TLS enforcement
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
X_FRAME_OPTIONS = "DENY"

if not DEBUG:
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "300"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env_flag("SECURE_HSTS_INCLUDE_SUBDOMAINS", False)
    SECURE_HSTS_PRELOAD = env_flag("SECURE_HSTS_PRELOAD", False)
    SECURE_SSL_REDIRECT = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True

# NES API Configuration
NES_API_URL = os.getenv("NES_API_URL", "https://nes.jawafdehi.org/api")

# NES Database Path - required for GitHub Actions queue processing only.
# Points to the local clone of the nes-db repository.
NES_DB_PATH = os.getenv("NES_DB_PATH")

# NGM Database Configuration (for read-only SQL endpoint)
NGM_QUERY_MAX_ROWS = int(os.getenv("NGM_QUERY_MAX_ROWS", "500"))

# Case Workflow Configuration
_case_workflows_work_dir_env = os.getenv("CASE_WORKFLOWS_WORK_DIR")
CASE_WORKFLOWS_WORK_DIR = (
    Path(_case_workflows_work_dir_env)
    if _case_workflows_work_dir_env
    else BASE_DIR / "workflow-runs"
)

# Cache Configuration
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "jawafdehi-cache",
        "TIMEOUT": 300,  # 5 minutes default
    }
}

# Jazzmin Configuration
JAZZMIN_SETTINGS = {
    "site_title": "Jawafdehi Admin",
    "site_header": "Jawafdehi",
    "site_brand": "Jawafdehi",
    "site_logo": "corruption-db-logo.png",
    "login_logo": "corruption-db-logo.png",
    "site_logo_classes": "img-circle",
    "site_icon": "corruption-db-logo.png",
    "welcome_sign": "Welcome to Jawafdehi Contributor Portal",
    "copyright": "Jawafdehi",
    "search_model": ["cases.Case", "cases.DocumentSource"],
    "user_avatar": None,
    # Top Menu
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Public API", "url": "/api/swagger", "new_window": True},
    ],
    # Side Menu
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["cases", "auth"],
    # Icons
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "cases.Case": "fas fa-gavel",
        "cases.DocumentSource": "fas fa-file-alt",
    },
    # UI Tweaks
    "custom_css": None,
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
}

# markdownx removed — replaced by EasyMDE editor widget
# MARKDOWNX_MARKDOWNIFY_FUNCTION = "markdownx.utils.markdownify"
# MARKDOWNX_MEDIA_PATH = "markdownx/"
# MARKDOWNX_UPLOAD_CONTENT_TYPES = ["image/jpeg", "image/png", "image/webp"]
# MARKDOWNX_UPLOAD_MAX_SIZE = 5 * 1024 * 1024


# ============================================================================
# Casework Review System (VOL-3) — rule-centered case-quality review
# ============================================================================
# The review app pulls a case (local DB by default, or live JDS API), converts
# its sources to markdown via likhit, and scores it against editable Rules using
# an AWS Bedrock LLM judge. See review/ for the engine.

# Where the review pipeline gets case data:
#   "local"  -> serialize a cases.Case from THIS database (offline; default).
#   "remote" -> fetch from the live Jawafdehi public API (needs JAWAFDEHI_API_TOKEN).
REVIEW_CASE_SOURCE = os.getenv("REVIEW_CASE_SOURCE", "local")

# Live JDS API (used by the seed_jawafdehi CLI and by REVIEW_CASE_SOURCE="remote").
JAWAFDEHI_API_BASE = os.getenv("JAWAFDEHI_API_BASE", "https://portal.jawafdehi.org/api")
JAWAFDEHI_API_TOKEN = os.getenv("JAWAFDEHI_API_TOKEN", "")
JAWAFDEHI_S3_BASE = os.getenv("JAWAFDEHI_S3_BASE", "https://s3.jawafdehi.org")

# AWS Bedrock (LLM judge). Distinct from the S3 storage creds above: the judge
# uses a named profile / cross-region inference profile model id.
AWS_PROFILE = os.getenv("REVIEW_AWS_PROFILE", os.getenv("AWS_PROFILE", ""))
AWS_REGION = os.getenv("AWS_REGION", "us-west-2")
BEDROCK_MODEL_ID = os.getenv("BEDROCK_MODEL_ID", "global.anthropic.claude-opus-4-8")
BEDROCK_MAX_WORKERS = int(os.getenv("BEDROCK_MAX_WORKERS", "8"))

# Converted source markdown cache + per-source conversion timeout.
SOURCE_MARKDOWN_DIR = Path(
    os.getenv("SOURCE_MARKDOWN_DIR", str(BASE_DIR / "review_source_markdown"))
)
SOURCE_MARKDOWN_DIR.mkdir(parents=True, exist_ok=True)
CONVERT_SOURCE_TIMEOUT = int(os.getenv("CONVERT_SOURCE_TIMEOUT", "180"))

# Max number of case reviews allowed to run CONCURRENTLY. Additional submitted
# reviews queue (status=pending) and start as running slots free up. Configurable
# via env so the operator can tune the parallel review throughput.
REVIEW_MAX_PARALLEL = int(os.getenv("REVIEW_MAX_PARALLEL", "3"))

# Casework job poller: the poller talks ONLY to the casework HTTP API (claim ->
# process locally -> submit result) and never touches the DB. It authenticates
# with a long-lived DRF auth token (Authorization: Token <key>) belonging to a
# dedicated service account — NOT a username/password login. Create the token
# with `manage.py drf_create_token <service-account-username>` and supply it via
# CASEWORK_POLLER_TOKEN. Locally the API is this same server on :40173.
CASEWORK_API_BASE = os.getenv(
    "CASEWORK_API_BASE", "http://127.0.0.1:40173/api/casework"
)
CASEWORK_POLLER_TOKEN = os.getenv("CASEWORK_POLLER_TOKEN", "")

# Base used to absolutize relative media URLs (e.g. a locally-stored MARKDOWN
# file served under /media/) when there is no request context. In production
# MEDIA_URL is already an absolute S3 URL so this is unused; locally it makes the
# stored markdown link a valid absolute URL.
MEDIA_PUBLIC_BASE = os.getenv("MEDIA_PUBLIC_BASE", "http://127.0.0.1:40173")
