"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

import dj_database_url
import sentry_sdk
import structlog as _structlog
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
from sentry_sdk.integrations.django import DjangoIntegration

from config.structlog_config import configure_structlog

load_dotenv()

configure_structlog()

_sentry_dsn = os.getenv("SENTRY_DSN")
if _sentry_dsn:
    sentry_sdk.init(
        dsn=_sentry_dsn,
        integrations=[
            DjangoIntegration(),
        ],
        traces_sample_rate=float(os.getenv("SENTRY_TRACES_SAMPLE_RATE", "1.0")),
        send_default_pii=False,
        environment=os.getenv("SENTRY_ENVIRONMENT", "production"),
    )


def get_env_list(name, default=""):
    value = os.getenv(name, default)
    return [item.strip() for item in value.split(",") if item.strip()]


def env_flag(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default

    normalized = value.strip().lower()
    if normalized in {"true", "1", "yes", "y", "on"}:
        return True
    if normalized in {"false", "0", "no", "n", "off"}:
        return False
    return default


def ensure_trailing_slash(value):
    if not value:
        return value
    return value if value.endswith("/") else f"{value}/"


def build_s3_storage_options(
    access_key,
    secret_key,
    bucket_name,
    region_name,
    endpoint_url,
    use_ssl,
    custom_domain=None,
):
    storage_options = {
        "access_key": access_key,
        "secret_key": secret_key,
        "bucket_name": bucket_name,
        "region_name": region_name,
        "endpoint_url": endpoint_url,
        "use_ssl": use_ssl,
        "querystring_auth": False,
    }

    if custom_domain:
        storage_options["custom_domain"] = custom_domain

    return storage_options


def build_media_url(
    explicit_media_url=None,
    custom_domain=None,
    endpoint_url=None,
    bucket_name=None,
    use_ssl=True,
):
    if explicit_media_url:
        return ensure_trailing_slash(explicit_media_url)

    if custom_domain:
        if custom_domain.startswith(("http://", "https://")):
            return ensure_trailing_slash(custom_domain)
        scheme = "https" if use_ssl else "http"
        return f"{scheme}://{ensure_trailing_slash(custom_domain)}"

    if endpoint_url and bucket_name:
        return f"{ensure_trailing_slash(endpoint_url)}{bucket_name}/"

    return "/media/"


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY or SECRET_KEY.startswith("django-insecure-"):
    raise ImproperlyConfigured(
        "SECRET_KEY environment variable must be set to a secure value. "
        "Generate one with: python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'"
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = get_env_list("ALLOWED_HOSTS", "")
if not DEBUG and not ALLOWED_HOSTS:
    raise ImproperlyConfigured(
        "ALLOWED_HOSTS environment variable must be set in production. "
        "Set it to a comma-separated list of allowed hostnames "
        "(e.g. ALLOWED_HOSTS=jawafdehi.org,beta.jawafdehi.org)."
    )

CSRF_TRUSTED_ORIGINS = get_env_list("CSRF_TRUSTED_ORIGINS")


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {
            "()": _structlog.stdlib.ProcessorFormatter,
            "processor": _structlog.processors.JSONRenderer(),
            "foreign_pre_chain": [
                _structlog.contextvars.merge_contextvars,
                _structlog.processors.TimeStamper(fmt="iso", utc=True),
                _structlog.stdlib.add_logger_name,
                _structlog.stdlib.add_log_level,
                _structlog.stdlib.ExtraAdder(),
            ],
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "json",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.server": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": os.getenv("ROOT_LOG_LEVEL", "INFO"),
    },
}


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "mozilla_django_oidc",
    "drf_spectacular",
    "django_filters",
    "corsheaders",
    "auditlog",
    "rules.apps.AutodiscoverRulesConfig",
    "cases",
    "nesq",
    "ngm",
    "case_workflows",
    # Casework Review System (VOL-3): rule-centered case-quality review.
    "review",
    "llm",
    # Wagtail CMS (headless) — public updates/news articles.
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail.api.v2",
    "wagtail",
    "modelcluster",
    "taggit",
    "content",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "config.middleware.RequestIdMiddleware",
    "config.middleware.ForcePrimaryReadsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "config.middleware.JWTAuditlogMiddleware",
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Where a successful session login redirects when no ?next= is supplied.
# The only session-login surface here is the Django admin (the casework portal
# uses JWT and never touches this), so send admin logins to the admin index
# instead of Django's nonexistent default of /accounts/profile/.
LOGIN_REDIRECT_URL = "/admin/"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# SSL-related PostgreSQL connection parameters that dj_database_url may place
# at the top level of the config dict when they appear as URL query params
# (e.g. ?sslmode=verify-ca&sslrootcert=/path/to/ca.pem). These need to be
# moved into OPTIONS for Django / psycopg2 to interpret them correctly.
_SSL_PARAMS = frozenset(
    {
        "sslmode",
        "sslrootcert",
        "sslcert",
        "sslkey",
        "sslcrl",
        "sslpassword",
        "sslcompression",
        "sslsni",
    }
)


def _apply_db_ssl_options(db_config):
    """Apply SSL options to a PostgreSQL database config.

    Sources (in priority order — first wins):
    1. URL query parameters already in the config dict
       (dj_database_url places them at the top level)
    2. Environment variables:
       - DATABASE_SSL_MODE            → sslmode
       - DATABASE_SSL_CA_CERT_FILE    → sslrootcert
       - DATABASE_SSL_CLIENT_CERT_FILE → sslcert
       - DATABASE_SSL_CLIENT_KEY_FILE  → sslkey

    If the engine is not PostgreSQL this is a no-op.
    """
    if db_config.get("ENGINE") != "django.db.backends.postgresql":
        return db_config

    options = db_config.setdefault("OPTIONS", {})

    # Move SSL params that came in via URL query string into OPTIONS.
    for param in _SSL_PARAMS:
        if param in db_config:
            options.setdefault(param, db_config.pop(param))

    # Apply from environment variables (won't override URL-provided values).
    ssl_mode = os.getenv("DATABASE_SSL_MODE")
    if ssl_mode:
        options.setdefault("sslmode", ssl_mode)

    ca_cert = os.getenv("DATABASE_SSL_CA_CERT_FILE") or os.getenv("SSL_CA_CERT_FILE")
    if ca_cert:
        options.setdefault("sslrootcert", ca_cert)

    client_cert = os.getenv("DATABASE_SSL_CLIENT_CERT_FILE") or os.getenv(
        "SSL_CLIENT_CERT_FILE"
    )
    if client_cert:
        options.setdefault("sslcert", client_cert)

    client_key = os.getenv("DATABASE_SSL_CLIENT_KEY_FILE") or os.getenv(
        "SSL_CLIENT_KEY_FILE"
    )
    if client_key:
        options.setdefault("sslkey", client_key)

    return db_config


# Handle secret interpolation for database URLs
def interpolate_db_url(url_env_name):
    url = os.getenv(url_env_name)
    if not url:
        return
    password = os.getenv("DATABASE_PASSWORD")
    if password:
        url = url.replace("${DATABASE_PASSWORD}", password)
        os.environ[url_env_name] = url


interpolate_db_url("DATABASE_URL")
interpolate_db_url("NGM_DATABASE_URL")
interpolate_db_url("DATABASE_READ_URL")
interpolate_db_url("NGM_DATABASE_READ_URL")

DATABASES = {
    "default": dj_database_url.config(
        default="sqlite:///db.sqlite3",
    )
}

# Dynamic interpolation of database password from environment variable
# This allows us to inject the password from Google Secret Manager at runtime
db_password = os.getenv("DATABASE_PASSWORD")
if db_password:
    for db_key in DATABASES:
        db_url = os.getenv(f"{db_key.upper()}_DATABASE_URL") or os.getenv(
            "DATABASE_URL"
        )
        if db_url and "${DATABASE_PASSWORD}" in db_url:
            DATABASES[db_key]["PASSWORD"] = db_password
            new_url = db_url.replace("${DATABASE_PASSWORD}", db_password)
            DATABASES[db_key] = dj_database_url.parse(new_url)

if os.getenv("NGM_DATABASE_URL"):
    DATABASES["ngm"] = dj_database_url.config(env="NGM_DATABASE_URL")
    if db_password and "${DATABASE_PASSWORD}" in os.getenv("NGM_DATABASE_URL"):
        new_url = os.getenv("NGM_DATABASE_URL").replace(
            "${DATABASE_PASSWORD}", db_password
        )
        DATABASES["ngm"] = dj_database_url.parse(new_url)


# Read-replica aliases for the primary/replica router (config/db_router.py).
# DATABASE_READ_URL / NGM_DATABASE_READ_URL point at the CNPG `pg-r` service
# (primary + standbys, read-only). A replica alias is created ONLY when its
# read URL is set; otherwise the router and the NGM read helper fall back to the
# primary, so dev, CI, and any single-endpoint deployment behave exactly as
# before the split (no second connection pool).
REPLICA_OF = {"default": "replica", "ngm": "ngm_replica"}


def _configure_replica(read_env_name, primary_alias):
    read_url = os.getenv(read_env_name)
    if read_url and primary_alias in DATABASES:
        DATABASES[REPLICA_OF[primary_alias]] = dj_database_url.parse(read_url)


_configure_replica("DATABASE_READ_URL", "default")
_configure_replica("NGM_DATABASE_READ_URL", "ngm")

# Apply SSL options to all PostgreSQL databases.
# Must run after password interpolation so that re-parsed configs also
# receive SSL options.
for db_key in DATABASES:
    _apply_db_ssl_options(DATABASES[db_key])

# Configure connection pooling for every PostgreSQL alias (incl. replicas).
for db_key, db_config in DATABASES.items():
    if db_config.get("ENGINE") == "django.db.backends.postgresql":
        db_config["CONN_MAX_AGE"] = 60
        db_config["CONN_HEALTH_CHECKS"] = True

# The replica aliases are read-only mirrors of their primaries. The test runner
# must not create/migrate a separate database for them — point each at its
# primary's test database so the suite exercises one consistent DB per pair.
for _primary, _replica in REPLICA_OF.items():
    if _replica in DATABASES:
        DATABASES[_replica].setdefault("TEST", {})["MIRROR"] = _primary

# Primary/replica routing: ORM reads -> `replica`, writes -> `default`.
DATABASE_ROUTERS = ["config.db_router.PrimaryReplicaRouter"]


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Authentication backends
AUTHENTICATION_BACKENDS = [
    "config.oidc.JawafdehiOIDCBackend",
    "rules.permissions.ObjectPermissionBackend",
    "django.contrib.auth.backends.ModelBackend",
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kathmandu"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Additional locations of static files
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Whitenoise configuration for serving static files
# Configure storage backend - use S3/R2 if AWS credentials are available, otherwise use FileSystemStorage
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME", "jawafdehi")
AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", "auto")
AWS_S3_ENDPOINT_URL = os.getenv("AWS_S3_ENDPOINT_URL")
AWS_S3_CUSTOM_DOMAIN = os.getenv("AWS_S3_CUSTOM_DOMAIN")
AWS_S3_USE_SSL = env_flag("AWS_S3_USE_SSL", True)

if AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY:
    # Use django-storages with S3 backend for both local (Minio) and cloud (R2/AWS S3)
    storage_options = build_s3_storage_options(
        access_key=AWS_ACCESS_KEY_ID,
        secret_key=AWS_SECRET_ACCESS_KEY,
        bucket_name=AWS_STORAGE_BUCKET_NAME,
        region_name=AWS_S3_REGION_NAME,
        endpoint_url=AWS_S3_ENDPOINT_URL,
        use_ssl=AWS_S3_USE_SSL,
        custom_domain=AWS_S3_CUSTOM_DOMAIN,
    )

    STORAGES = {
        "default": {
            "BACKEND": "cases.storage.HashedFilenameS3Boto3Storage",
            "OPTIONS": storage_options,
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
else:
    # Development: use FileSystemStorage
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

# Media Files Configuration
MEDIA_URL = build_media_url(
    explicit_media_url=os.getenv("MEDIA_URL"),
    custom_domain=AWS_S3_CUSTOM_DOMAIN,
    endpoint_url=AWS_S3_ENDPOINT_URL,
    bucket_name=(
        AWS_STORAGE_BUCKET_NAME if AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY else None
    ),
    use_ssl=AWS_S3_USE_SSL,
)
MEDIA_ROOT = os.getenv("MEDIA_ROOT", BASE_DIR / "media")

# Wagtail CMS configuration (headless — serves public updates/news via API v2).
# Wagtail images/documents share the default storage; HashedFilenameS3Boto3Storage
# leaves their namespaced upload paths untouched (see cases/storage.py).
WAGTAIL_SITE_NAME = "Jawafdehi Newsroom"
# Base URL used for absolute links in the admin (notification emails, previews).
# Not used for public delivery — the SPA consumes the API v2 endpoints.
WAGTAILADMIN_BASE_URL = os.getenv("WAGTAILADMIN_BASE_URL", "https://api.jawafdehi.org")
WAGTAILSEARCH_BACKENDS = {
    "default": {
        "BACKEND": "wagtail.search.backends.database",
    }
}
WAGTAILDOCS_EXTENSIONS = ["csv", "docx", "pdf", "pptx", "rtf", "txt", "xlsx", "zip"]
WAGTAILDOCS_MAX_UPLOAD_SIZE = 10 * 1024 * 1024  # 10 MB, matches case upload limit
WAGTAILIMAGES_MAX_UPLOAD_SIZE = 10 * 1024 * 1024
# Headless: pages are delivered via the API, not Wagtail's own routing.
WAGTAIL_APPEND_SLASH = False
# Complex StreamField pages can exceed Django's default form field cap.
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10_000

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Detect test runner to disable throttling during tests (global rate limits
# applied by JAW-60 would cause 429s in the test suite).
TESTING = os.getenv("TESTING") == "true" or any("pytest" in arg for arg in sys.argv)

# REST Framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "config.oidc.OIDCJWTAuthentication",
        # Per-user DRF tokens for service/scripted access (e.g. the MCP stdio
        # fallback). The previous impersonation subclass (trusting a spoofable
        # X-Jawafdehi-User-Id header) was removed in favor of OIDC bearer auth.
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

if not TESTING:
    REST_FRAMEWORK["DEFAULT_THROTTLE_CLASSES"] = [
        "cases.throttles.AnonRateThrottle",
        "cases.throttles.RoleBasedUserRateThrottle",
    ]
    # RoleBasedUserRateThrottle picks the highest tier the user qualifies for:
    # staff (Admin/Moderator/superuser/is_staff) > contributor > user.
    REST_FRAMEWORK["DEFAULT_THROTTLE_RATES"] = {
        "anon": "1000/hour",
        "user": "1000/hour",
        "contributor": "2500/hour",
        "staff": "5000/hour",
    }


SPECTACULAR_SETTINGS = {
    "TITLE": "Jawafdehi Public Accountability API",
    "DESCRIPTION": """
Public API for the Jawafdehi accountability platform.

This API provides read-only access to published cases of alleged corruption
and misconduct by public entities in Nepal.

## Features

- **Browse Cases**: List all published cases with filtering and search
- **View Details**: Get complete case information including evidence and timeline
- **Audit History**: Access version history for published cases
- **Document Sources**: Browse evidence sources associated with published cases

## Access

All endpoints are public and do not require authentication. Only published
cases (state=PUBLISHED) are accessible through this API.

## Filtering & Search

The cases endpoint supports:
- Filtering by case type and tags
- Full-text search across title, description, and key allegations
- Pagination (20 items per page)
    """,
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": "/api/",
    "SERVERS": None,  # Use None to auto-detect from request
    "TAGS": [
        {"name": "cases", "description": "Operations related to accountability cases"},
        {
            "name": "sources",
            "description": "Operations related to document sources and evidence",
        },
    ],
    "ENUM_NAME_OVERRIDES": {
        "CaseTypeEnum": "cases.models.CaseType",
    },
}

# CORS
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = get_env_list(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:8080,http://127.0.0.1:8080,https://jawafdehi.org,https://beta.jawafdehi.org",
)
# Allow the casework portal SPA cross-origin from:
#   - the project's Cloudflare workers.dev domain and its per-version preview
#     subdomains (e.g. abc123.newnepal.workers.dev)
#   - any jawafdehi.org subdomain (e.g. beta., portal., preview hosts)
# to call the API (e.g. the JWT token endpoint).
CORS_ALLOWED_ORIGIN_REGEXES = get_env_list(
    "CORS_ALLOWED_ORIGIN_REGEXES",
    ",".join(
        [
            r"^https://([a-z0-9-]+\.)?newnepal\.workers\.dev$",
            r"^https://([a-z0-9-]+\.)?jawafdehi\.org$",
        ]
    ),
)
CORS_ALLOW_METHODS = ["GET", "HEAD", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]
CORS_ALLOW_CREDENTIALS = True

# Keep Django's CSRF origin validation aligned with credentialed CORS writes.
if not CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS.copy()

# Security headers and TLS enforcement
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
X_FRAME_OPTIONS = "DENY"

if not DEBUG:
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "300"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env_flag("SECURE_HSTS_INCLUDE_SUBDOMAINS", False)
    SECURE_HSTS_PRELOAD = env_flag("SECURE_HSTS_PRELOAD", False)
    SECURE_SSL_REDIRECT = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True

# NES API Configuration
NES_API_URL = os.getenv("NES_API_URL", "https://nes.jawafdehi.org/api")

# NES Database Path - required for GitHub Actions queue processing only.
# Points to the local clone of the nes-db repository.
NES_DB_PATH = os.getenv("NES_DB_PATH")

# NGM Database Configuration (for read-only SQL endpoint)
NGM_QUERY_MAX_ROWS = int(os.getenv("NGM_QUERY_MAX_ROWS", "500"))

# Case Workflow Configuration
_case_workflows_work_dir_env = os.getenv("CASE_WORKFLOWS_WORK_DIR")
CASE_WORKFLOWS_WORK_DIR = (
    Path(_case_workflows_work_dir_env)
    if _case_workflows_work_dir_env
    else BASE_DIR / "workflow-runs"
)

# Cache Configuration
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "jawafdehi-cache",
        "TIMEOUT": 300,  # 5 minutes default
    }
}

# Jazzmin Configuration
JAZZMIN_SETTINGS = {
    "site_title": "Jawafdehi Admin",
    "site_header": "Jawafdehi",
    "site_brand": "Jawafdehi",
    "site_logo": "corruption-db-logo.png",
    "login_logo": "corruption-db-logo.png",
    "site_logo_classes": "img-circle",
    "site_icon": "corruption-db-logo.png",
    "welcome_sign": "Welcome to Jawafdehi Contributor Portal",
    "copyright": "Jawafdehi",
    "search_model": ["cases.Case", "cases.DocumentSource"],
    "user_avatar": None,
    # Top Menu
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Public API", "url": "/api/swagger", "new_window": True},
    ],
    # Side Menu
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["cases", "auth"],
    # Icons
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "cases.Case": "fas fa-gavel",
        "cases.DocumentSource": "fas fa-file-alt",
    },
    # UI Tweaks
    "custom_css": None,
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
}

# markdownx removed — replaced by EasyMDE editor widget
# MARKDOWNX_MARKDOWNIFY_FUNCTION = "markdownx.utils.markdownify"
# MARKDOWNX_MEDIA_PATH = "markdownx/"
# MARKDOWNX_UPLOAD_CONTENT_TYPES = ["image/jpeg", "image/png", "image/webp"]
# MARKDOWNX_UPLOAD_MAX_SIZE = 5 * 1024 * 1024


# ============================================================================
# Casework Review System (VOL-3) — rule-centered case-quality review
# ============================================================================
# The review app pulls a case (local DB by default, or live JDS API), converts
# its sources to markdown via likhit, and scores it against editable Rules using
# an AWS Bedrock LLM judge. See review/ for the engine.

# Where the review pipeline gets case data:
#   "local"  -> serialize a cases.Case from THIS database (offline; default).
#   "remote" -> fetch from the live Jawafdehi public API (needs JAWAFDEHI_API_TOKEN).
REVIEW_CASE_SOURCE = os.getenv("REVIEW_CASE_SOURCE", "local")

# Live JDS API (used by the seed_jawafdehi CLI and by REVIEW_CASE_SOURCE="remote").
JAWAFDEHI_API_BASE = os.getenv("JAWAFDEHI_API_BASE", "https://portal.jawafdehi.org/api")
JAWAFDEHI_API_TOKEN = os.getenv("JAWAFDEHI_API_TOKEN", "")
JAWAFDEHI_S3_BASE = os.getenv("JAWAFDEHI_S3_BASE", "https://s3.jawafdehi.org")

# AWS Bedrock (LLM judge). Distinct from the S3 storage creds above: the judge
# uses a named profile / cross-region inference profile model id.
AWS_PROFILE = os.getenv("REVIEW_AWS_PROFILE", os.getenv("AWS_PROFILE", ""))
AWS_REGION = os.getenv("AWS_REGION", "us-west-2")
BEDROCK_MODEL_ID = os.getenv("BEDROCK_MODEL_ID", "global.anthropic.claude-opus-4-8")
BEDROCK_MAX_WORKERS = int(os.getenv("BEDROCK_MAX_WORKERS", "8"))
# Prompt-cache the shared rule-grading prefix (case data + source excerpts) so it
# is billed once per case instead of once per (rule x sample) call. Kill switch
# for regions/models where Bedrock prompt caching is unavailable.
BEDROCK_PROMPT_CACHE = env_flag("BEDROCK_PROMPT_CACHE", default=True)
# Tiered model routing: high-stakes GATE rules (a low score can REJECT the case)
# are graded by the premium model above; routine non-gate rules and the narrative
# use this cheaper SKU. Defaults to the premium model id, so routing is a no-op
# until a real cheaper model id is configured for this deployment's region/account
# (the operator picks the SKU — we never guess one that may not exist).
BEDROCK_MODEL_ID_CHEAP = os.getenv("BEDROCK_MODEL_ID_CHEAP", BEDROCK_MODEL_ID)

# Review-judge LLM provider. "bedrock" (default) invokes AWS Bedrock directly;
# "proxy" routes through the in-house OpenAI-compatible llm-proxy so the judge can
# run on non-Bedrock models without code changes. This is provider flexibility,
# not a Bedrock replacement — the default preserves the existing behaviour.
REVIEW_LLM_PROVIDER = os.getenv("REVIEW_LLM_PROVIDER", "bedrock").strip().lower()
REVIEW_LLM_PROVIDER_PREMIUM = (
    os.getenv("REVIEW_LLM_PROVIDER_PREMIUM", REVIEW_LLM_PROVIDER).strip().lower()
)
REVIEW_LLM_PROVIDER_CHEAP = (
    os.getenv("REVIEW_LLM_PROVIDER_CHEAP", REVIEW_LLM_PROVIDER).strip().lower()
)
# llm-proxy (OpenAI-compatible) connection. In-cluster callers MUST use the
# internal ClusterIP base URL: the public llm-proxy.jawafdehi.org host sits behind
# a Cloudflare WAF that 403s the OpenAI SDK user-agent.
LLM_PROXY_BASE_URL = os.getenv(
    "LLM_PROXY_BASE_URL", "http://llm-proxy.app.svc.cluster.local/v1"
)
LLM_PROXY_API_KEY = os.getenv("LLM_PROXY_API_KEY", "")
# Override the OpenAI SDK User-Agent when fronting the proxy through the public
# Cloudflare-WAF host (which 403s the default SDK UA). Leave empty for the
# in-cluster ClusterIP path.
LLM_PROXY_USER_AGENT = os.getenv("LLM_PROXY_USER_AGENT", "")
# Proxy model ids per tier (the proxy registry's names differ from Bedrock SKU
# ids, so they are configured separately). Premium grades hard GATE rules; cheap
# grades routine rules + the narrative. Cheap defaults to premium, so tiering is a
# no-op until a real cheaper id is set. Operators pick the ids — we never guess.
LLM_PROXY_MODEL_ID = os.getenv("LLM_PROXY_MODEL_ID", "")
LLM_PROXY_MODEL_ID_CHEAP = os.getenv("LLM_PROXY_MODEL_ID_CHEAP", LLM_PROXY_MODEL_ID)
# The proxied models (gpt-5.x, deepseek) are *reasoning* models: max_tokens caps
# reasoning + answer combined. The judge's tight caps (tuned for Claude's direct
# output) would be spent on reasoning, leaving the JSON answer empty/truncated, so
# we add this headroom to every proxy call's budget. Bedrock (Claude) is unaffected.
LLM_PROXY_REASONING_HEADROOM = int(os.getenv("LLM_PROXY_REASONING_HEADROOM", "8000"))

# CLI-harness providers (codex_cli / claude_cli) — invoke locally-installed CLIs
# authenticated by the user's SUBSCRIPTION (never API keys).
CODEX_CLI_BIN = os.getenv("CODEX_CLI_BIN", "codex")
CLAUDE_CLI_BIN = os.getenv("CLAUDE_CLI_BIN", "claude")
CODEX_HOME = os.getenv("CODEX_HOME", "")  # if set, used as the codex auth dir
CLAUDE_CLI_HOME = os.getenv(
    "CLAUDE_CLI_HOME", ""
)  # if set, used as $HOME for claude creds
CODEX_MODEL_ID = os.getenv("CODEX_MODEL_ID", "")
CLAUDE_CLI_MODEL_ID = os.getenv("CLAUDE_CLI_MODEL_ID", "")
# Per-tier claude model selection ("opus"/"sonnet"/"haiku" or full ids) — gates
# vs routine. Fall back to CLAUDE_CLI_MODEL_ID, then the CLI default.
CLAUDE_CLI_MODEL_PREMIUM = os.getenv("CLAUDE_CLI_MODEL_PREMIUM", "")
CLAUDE_CLI_MODEL_CHEAP = os.getenv("CLAUDE_CLI_MODEL_CHEAP", "")
# claude -p reasoning budget: low/medium/high/xhigh/max ("" -> CLI default).
CLAUDE_CLI_EFFORT = os.getenv("CLAUDE_CLI_EFFORT", "")
REVIEW_CLI_MAX_WORKERS = int(os.getenv("REVIEW_CLI_MAX_WORKERS", "2"))
REVIEW_CLI_TIMEOUT = int(os.getenv("REVIEW_CLI_TIMEOUT", "300"))
REVIEW_CLI_MAX_RETRIES = int(os.getenv("REVIEW_CLI_MAX_RETRIES", "3"))
# Batch this many rules into ONE grading call on CLI-harness providers (which
# can't reuse prompt cache across subprocess calls). 1 disables batching (per-rule
# path; use for A/B vs batched). Only affects codex_cli / claude_cli; bedrock/proxy
# always use the per-rule + prompt-cache path.
REVIEW_RULE_BATCH_SIZE = int(os.getenv("REVIEW_RULE_BATCH_SIZE", "8"))

# Agentic claude provider ("claude_agent") — unlike claude_cli (locked to a
# single read-only plan-mode turn), this lets the claude CLI RUN WILD: multi-turn,
# fetching its own sources through a fixed MCP toolset, then self-judging and
# emitting the expected JSON. A cheaper model judges completeness and we re-run
# until done or the iteration cap. Auth is the same seeded subscription OAuth as
# claude_cli (no API keys). NOTE: the 2026-06-15 Agent-SDK billing split (paused,
# may reactivate) would bill this headless/agent usage from a separate full-rate
# pool — hence the hard CLAUDE_AGENT_MAX_ITERS cap.
CLAUDE_AGENT_BIN = os.getenv("CLAUDE_AGENT_BIN", os.getenv("CLAUDE_CLI_BIN", "claude"))
# $HOME holding .claude/.credentials.json (subscription OAuth). Defaults to the
# same dir claude_cli uses so the existing seeded creds are reused.
CLAUDE_AGENT_HOME = os.getenv("CLAUDE_AGENT_HOME", os.getenv("CLAUDE_CLI_HOME", ""))
CLAUDE_AGENT_MODEL_ID = os.getenv("CLAUDE_AGENT_MODEL_ID", "")
CLAUDE_AGENT_MODEL_PREMIUM = os.getenv("CLAUDE_AGENT_MODEL_PREMIUM", "")
CLAUDE_AGENT_MODEL_CHEAP = os.getenv("CLAUDE_AGENT_MODEL_CHEAP", "")
# Path to the MCP config JSON handed to `claude --mcp-config`. Defines the ONLY
# servers/tools the agent may reach. Empty = no MCP (agent runs tool-less).
CLAUDE_AGENT_MCP_CONFIG = os.getenv("CLAUDE_AGENT_MCP_CONFIG", "")
# Space-separated tool allowlist. The agent reads its PRE-STAGED case materials
# (Read/Glob/Grep, confined to the staging dir by --add-dir) and may call a minimal
# MCP set (convert_date now; extend as new MCP tools are needed). It does NOT fetch
# its own sources — those are pre-converted and staged for it.
CLAUDE_AGENT_ALLOWED_TOOLS = os.getenv(
    "CLAUDE_AGENT_ALLOWED_TOOLS",
    "Read Glob Grep mcp__jawafdehi__convert_date",
)
# Built-in tools explicitly denied: no shell, no writes, no web. (Read/Glob/Grep are
# allowed above but scoped to the staging dir via cwd + --add-dir.)
CLAUDE_AGENT_DISALLOWED_TOOLS = os.getenv(
    "CLAUDE_AGENT_DISALLOWED_TOOLS",
    "Bash Write Edit MultiEdit NotebookEdit WebFetch WebSearch",
)
# Upper bound on agentic turns within a single run (runaway guard). Min 1 — a
# zero/negative cap would make claude abort before producing a result.
CLAUDE_AGENT_MAX_TURNS = max(1, int(os.getenv("CLAUDE_AGENT_MAX_TURNS", "40")))
# Outer run-wild -> judge -> rerun loop cap. Mandatory ceiling (see billing note).
CLAUDE_AGENT_MAX_ITERS = max(1, int(os.getenv("CLAUDE_AGENT_MAX_ITERS", "3")))
# How many times to grade the full rule batch (samples per rule). The agent grades
# all of a tier's rules in one call; running it N times gives each rule a real
# mean+variance/confidence instead of a single-pass std 0. Cost scales linearly.
CLAUDE_AGENT_SAMPLES = max(1, int(os.getenv("CLAUDE_AGENT_SAMPLES", "2")))
# Provider used to judge work completeness each iteration. Defaults to the cheap
# review provider. If it resolves to claude_agent itself, only the structural
# (valid-JSON) check runs to avoid recursion.
CLAUDE_AGENT_JUDGE_PROVIDER = os.getenv(
    "CLAUDE_AGENT_JUDGE_PROVIDER", REVIEW_LLM_PROVIDER_CHEAP
)
CLAUDE_AGENT_TIMEOUT = max(1, int(os.getenv("CLAUDE_AGENT_TIMEOUT", "900")))

# Converted source markdown cache + per-source conversion timeout.
SOURCE_MARKDOWN_DIR = Path(
    os.getenv("SOURCE_MARKDOWN_DIR", str(BASE_DIR / "review_source_markdown"))
)
SOURCE_MARKDOWN_DIR.mkdir(parents=True, exist_ok=True)
CONVERT_SOURCE_TIMEOUT = int(os.getenv("CONVERT_SOURCE_TIMEOUT", "180"))

# Use LibreOffice (headless) to convert legacy Word .doc / .docx sources to a
# clean .docx before markdown extraction. LibreOffice handles files the bundled
# antiword crashes on or rejects, but it is a heavy dependency (~1GB installed)
# that prod does NOT ship, so this defaults OFF and the converter uses the
# lighter likhit/antiword path. An operator running the reprocess command on a
# box that HAS LibreOffice (e.g. a one-off backfill host) can opt in with
# LIBREOFFICE_DOC_CONVERSION=true. When enabled but the binary is absent, the
# converter degrades to the fallback automatically (no hard dependency).
LIBREOFFICE_DOC_CONVERSION = (
    os.getenv("LIBREOFFICE_DOC_CONVERSION", "false").lower() == "true"
)
# Optional explicit path to the soffice/libreoffice binary; otherwise PATH is
# searched (including the versioned `libreoffice26.2` name).
LIBREOFFICE_BINARY = os.getenv("LIBREOFFICE_BINARY", "")

# Max number of case reviews allowed to run CONCURRENTLY. Additional submitted
# reviews queue (status=pending) and start as running slots free up. Configurable
# via env so the operator can tune the parallel review throughput.
REVIEW_MAX_PARALLEL = int(os.getenv("REVIEW_MAX_PARALLEL", "3"))

# Casework job poller: the poller talks ONLY to the casework HTTP API (claim ->
# process locally -> submit result) and never touches the DB. It authenticates
# with a long-lived DRF auth token (Authorization: Token <key>) belonging to a
# dedicated service account — NOT a username/password login. Create the token
# with `manage.py drf_create_token <service-account-username>` and supply it via
# CASEWORK_POLLER_TOKEN. Locally the API is this same server on :40173.
CASEWORK_API_BASE = os.getenv(
    "CASEWORK_API_BASE", "http://127.0.0.1:40173/api/casework"
)
CASEWORK_POLLER_TOKEN = os.getenv("CASEWORK_POLLER_TOKEN", "")

# Base used to absolutize relative media URLs (e.g. a locally-stored MARKDOWN
# file served under /media/) when there is no request context. In production
# MEDIA_URL is already an absolute S3 URL so this is unused; locally it makes the
# stored markdown link a valid absolute URL.
MEDIA_PUBLIC_BASE = os.getenv("MEDIA_PUBLIC_BASE", "http://127.0.0.1:40173")

# ============================================================================
# OIDC Configuration (auth provider — currently Zitadel, but kept provider-neutral)
# ============================================================================

OIDC_ISSUER = os.getenv("OIDC_ISSUER", "https://auth.jawafdehi.org")
OIDC_JWKS_URL = os.getenv("OIDC_JWKS_URL", f"{OIDC_ISSUER}/oauth/v2/keys")
# The audience (provider project/resource id) the API tokens must carry. Required
# in any real environment — set via env, not hardcoded.
OIDC_API_AUDIENCE = os.getenv("OIDC_API_AUDIENCE", "")

# Mozilla Django OIDC configuration for admin SSO.
# The admin app is a PUBLIC client (PKCE, no client secret): OIDC_RP_CLIENT_SECRET
# stays defined-but-empty (mozilla-django-oidc requires the setting to exist), and
# JawafdehiOIDCBackend.get_token drops the empty secret from the token request.
OIDC_RP_CLIENT_ID = os.getenv("OIDC_RP_CLIENT_ID", "")
OIDC_RP_CLIENT_SECRET = os.getenv("OIDC_RP_CLIENT_SECRET", "")
OIDC_USE_PKCE = True
OIDC_RP_SIGN_ALGO = "RS256"
OIDC_RP_SCOPES = "openid email profile"
OIDC_OP_AUTHORIZATION_ENDPOINT = f"{OIDC_ISSUER}/oauth/v2/authorize"
OIDC_OP_TOKEN_ENDPOINT = f"{OIDC_ISSUER}/oauth/v2/token"
OIDC_OP_USER_ENDPOINT = f"{OIDC_ISSUER}/oidc/v1/userinfo"
OIDC_OP_JWKS_ENDPOINT = OIDC_JWKS_URL
LOGIN_REDIRECT_URL = "/admin/"
LOGOUT_REDIRECT_URL = "/admin/login/"
LOGIN_URL = "/oidc/authenticate/"
# Route the Wagtail admin (/newsroom) through the same OIDC SSO flow instead of
# Wagtail's built-in username/password form. require_admin_access redirects
# unauthenticated users here (with ?next=), so the OIDC callback returns them to
# the newsroom. The /newsroom/login/ form is also redirected (see config/urls.py).
WAGTAILADMIN_LOGIN_URL = LOGIN_URL
