# Generated by Django 5.2.15 on 2026-07-29 22:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseUpdateProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_slug', models.SlugField()),
                ('case_title', models.CharField(blank=True, default='', max_length=200)),
                ('source_kind', models.CharField(choices=[('ngm_docket', 'Court docket'), ('court_order', 'Court order'), ('ciaa_press', 'CIAA press release'), ('news', 'News'), ('caseworker', 'Caseworker')], max_length=20)),
                ('intent', models.JSONField()),
                ('confidence', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], db_index=True, default='pending', max_length=12)),
                ('source', models.CharField(blank=True, default='', max_length=500)),
                ('detected_by', models.CharField(max_length=100)),
                ('dedup_key', models.CharField(db_index=True, max_length=300, unique=True)),
                ('supersedes', models.CharField(blank=True, default='', max_length=64)),
                ('origin_subject', models.CharField(blank=True, default='', max_length=100)),
                ('origin_msg_id', models.CharField(blank=True, default='', max_length=100)),
                ('subject_refs', models.JSONField(blank=True, default=list)),
                ('reviewer', models.CharField(blank=True, default='', max_length=100)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='case_propos_status_ffc690_idx'), models.Index(fields=['case_slug', 'status'], name='case_propos_case_sl_d4311f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('confidence__gte', 0.0), ('confidence__lte', 1.0)), name='case_proposal_confidence_between_0_and_1')],
            },
        ),
    ]
