# Generated by Django 5.2.15 on 2026-07-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    """Drop the unused `supersedes` field and the dead `superseded` status.

    Neither was ever written: `supersedes` had no producer and nothing anywhere set
    status to `superseded`, so the supersede lifecycle existed only as vocabulary.
    Reject-stickiness rides on the unique `dedup_key`, not on this. The DROP COLUMN
    is safe because the table was empty when this landed (the app shipped a day
    earlier and only automation-fed proposals populate it); the AlterField is
    Python-level only, since `choices` is not enforced in Postgres.
    """

    dependencies = [
        ('case_proposals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseupdateproposal',
            name='supersedes',
        ),
        migrations.AlterField(
            model_name='caseupdateproposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=12),
        ),
    ]
