# Generated by Django 5.2.15 on 2026-08-25 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('label_ne', models.CharField(max_length=120)),
                ('label_en', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('active', 'Active'), ('deprecated', 'Deprecated'), ('merged', 'Merged')], default='proposed', max_length=16)),
                ('sort_order', models.IntegerField(default=0, help_text="§12 'approved priority' — the tie-break above alphabetical. Explicit because sorting Devanagari labels alphabetically needs a locale-aware collation that Postgres and Python do not agree on by default.")),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broader', models.ForeignKey(blank=True, help_text='A wider tag this rolls up into. A case tagged land-grab is also a land case, so the indexer writes both. One level only.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='narrower', to='case_tags.tag')),
                ('merged_into', models.ForeignKey(blank=True, help_text='Replacement tag. Required when status is merged (§12).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merged_from', to='case_tags.tag')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TagAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='ALREADY NORMALIZED — the output of normalize(), not the raw value.', max_length=200, unique=True)),
                ('retired_reason', models.CharField(blank=True, help_text='Why it was dropped, e.g. not-a-tag-money-amount. Set iff tag is null.', max_length=64)),
                ('source', models.CharField(blank=True, help_text='The raw value this key came from.', max_length=200)),
                ('tag', models.ForeignKey(blank=True, help_text='Null when this value was retired rather than mapped.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='case_tags.tag')),
            ],
            options={
                'verbose_name_plural': 'tag aliases',
            },
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'merged'), _negated=True), ('merged_into__isnull', False), _connector='OR'), name='case_tags_merged_needs_target'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.CheckConstraint(condition=models.Q(('broader', models.F('id')), _negated=True), name='case_tags_broader_not_self'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.CheckConstraint(condition=models.Q(('merged_into', models.F('id')), _negated=True), name='case_tags_merged_into_not_self'),
        ),
        migrations.AddConstraint(
            model_name='tagalias',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('retired_reason', ''), ('tag__isnull', False)), models.Q(('tag__isnull', True), models.Q(('retired_reason', ''), _negated=True)), _connector='OR'), name='case_tags_alias_maps_or_explains'),
        ),
    ]
