# Generated by Django 5.2.15 on 2026-08-24 10:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.SlugField(max_length=60, primary_key=True, serialize=False)),
                ('label_ne', models.CharField(blank=True, max_length=200, null=True)),
                ('label_ne_composed', models.JSONField(blank=True, null=True)),
                ('label_en', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('active', 'Active'), ('deprecated', 'Deprecated'), ('merged', 'Merged')], db_index=True, default='proposed', max_length=12)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merged_from', to='case_tags.tag')),
            ],
            options={
                'ordering': ['axis__sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TagAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_index=True, max_length=300, unique=True)),
                ('source', models.CharField(choices=[('seed', 'Seeded from policy'), ('llm', 'Written by the tagger'), ('human', 'Entered by a human in the admin')], default='llm', max_length=8)),
                ('approved_by', models.CharField(blank=True, default='', max_length=100)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='case_tags.tag')),
            ],
            options={
                'verbose_name_plural': 'tag aliases',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='TagAxis',
            fields=[
                ('id', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('label_ne', models.CharField(max_length=100)),
                ('label_en', models.CharField(max_length=100)),
                ('min_per_case', models.PositiveSmallIntegerField(default=0)),
                ('max_per_case', models.PositiveSmallIntegerField(default=3)),
                ('highlighted', models.BooleanField(default=False)),
                ('members', models.CharField(choices=[('enumerated', 'Enumerated here'), ('entities', 'From the case entities relation'), ('external', 'From a fixed external list')], default='enumerated', max_length=12)),
                ('set_by', models.CharField(blank=True, default='', max_length=40)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('note', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'tag axes',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('max_per_case__gte', models.F('min_per_case'))), name='tag_axis_max_at_least_min')],
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='axis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='case_tags.tagaxis'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('merged_into__isnull', False), ('status', 'merged')), models.Q(models.Q(('status', 'merged'), _negated=True), ('merged_into__isnull', True)), _connector='OR'), name='tag_merged_iff_merged_into'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.CheckConstraint(condition=models.Q(('merged_into', models.F('id')), _negated=True), name='tag_not_merged_into_itself'),
        ),
    ]
