# Generated by Django 5.2.15 on 2026-08-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_tags', '0002_seed_vocabulary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagProposal',
        ),
        migrations.AlterField(
            model_name='tagalias',
            name='source',
            field=models.CharField(choices=[('seed', 'Seeded from policy'), ('llm', 'Written by the tagger'), ('human', 'Entered by a human in the admin')], default='llm', max_length=8),
        ),
    ]
