# Generated by Django 5.2.15 on 2026-06-28 05:15

import ngm_service.courts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blacklistedfirm",
            name="nes_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=300,
                null=True,
                validators=[ngm_service.courts.models.validate_entity_iri],
            ),
        ),
        migrations.AlterField(
            model_name="caseentity",
            name="nes_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=300,
                null=True,
                validators=[ngm_service.courts.models.validate_entity_iri],
            ),
        ),
        migrations.AlterField(
            model_name="courtcase",
            name="nes_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=300,
                null=True,
                validators=[ngm_service.courts.models.validate_entity_iri],
            ),
        ),
    ]
