# Generated by Django 5.2.9 on 2026-06-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0024_alter_chat_user_identity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseentityrelationship",
            name="relationship_type",
            field=models.CharField(
                choices=[
                    ("alleged", "Alleged"),
                    ("accused", "Accused"),
                    ("related", "Related"),
                    ("witness", "Witness"),
                    ("opposition", "Opposition"),
                    ("victim", "Victim"),
                    ("location", "Location"),
                    ("respondent", "प्रत्यर्थी (respondent)"),
                    ("petitioner", "रिट निवेदक (petitioner)"),
                ],
                help_text="Type of relationship between case and entity",
                max_length=20,
            ),
        ),
    ]
