# Generated by Django 5.2.9 on 2026-06-11 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0025_add_respondent_petitioner_relation_types"),
        ("cases", "0025_convert_url_list_to_dict"),
    ]

    operations = []
