# Generated by Django 5.2.9 on 2026-06-12 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0032_backfill_source_link_role_raw"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentsource",
            name="uploaded_content_type",
        ),
        migrations.RemoveField(
            model_name="documentsource",
            name="uploaded_file",
        ),
        migrations.RemoveField(
            model_name="documentsource",
            name="uploaded_file_size",
        ),
        migrations.RemoveField(
            model_name="documentsource",
            name="uploaded_filename",
        ),
        migrations.DeleteModel(
            name="DocumentSourceUpload",
        ),
    ]
