# Generated by Django 5.2.15 on 2026-06-28 05:07
#
# The GIN index on StoredEntity.data is declared in the model's
# Meta.indexes (so model state / `makemigrations --check` see it), but it is
# created at the DATABASE level only on PostgreSQL. GIN is a Postgres-only index
# access method; on sqlite (the DB-less test / local fallback) a `USING gin`
# statement is meaningless, and Django's sqlite backend would silently create a
# plain b-tree index of the same name instead — which is misleading and useless
# for JSONB containment. So the AddIndex is split with
# SeparateDatabaseAndState: the *state* op records the index in the model state
# (keeping makemigrations consistent), and the *database* op runs the real
# `CREATE INDEX ... USING gin` guarded to the postgresql vendor (a no-op on
# sqlite). See entities.models.StoredEntity.

import django.contrib.postgres.indexes
from django.db import migrations, models


def _create_gin_index(apps, schema_editor):
    """Create the JSONB GIN index — PostgreSQL only (no-op elsewhere)."""
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        'CREATE INDEX IF NOT EXISTS "ix_entities_data_gin" '
        'ON "entities" USING gin ("data")'
    )


def _drop_gin_index(apps, schema_editor):
    """Reverse of _create_gin_index — PostgreSQL only (no-op elsewhere)."""
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute('DROP INDEX IF EXISTS "ix_entities_data_gin"')


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeldEntity",
            fields=[
                ("iri", models.TextField(primary_key=True, serialize=False)),
                ("entity_data", models.JSONField()),
                ("sources", models.JSONField()),
                ("reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "db_table": "held_entities",
            },
        ),
        migrations.CreateModel(
            name="StoredAuthor",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("data", models.JSONField()),
            ],
            options={
                "db_table": "authors",
            },
        ),
        migrations.CreateModel(
            name="StoredEntity",
            fields=[
                ("iri", models.TextField(primary_key=True, serialize=False)),
                ("entity_type", models.TextField(db_index=True)),
                ("prefix", models.TextField(db_index=True)),
                ("slug", models.TextField(db_index=True)),
                ("data", models.JSONField()),
                ("version", models.IntegerField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "entities",
                "indexes": [
                    models.Index(fields=["entity_type"], name="ix_entities_type"),
                ],
            },
        ),
        migrations.CreateModel(
            name="StoredVersion",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("subject_iri", models.TextField(db_index=True)),
                ("version_number", models.IntegerField()),
                ("author_id", models.TextField()),
                ("data", models.JSONField()),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "versions",
                "indexes": [
                    models.Index(
                        fields=["subject_iri", "version_number"],
                        name="ix_versions_subject",
                    )
                ],
            },
        ),
        # GIN index on StoredEntity.data. State op records it in the model state
        # (so makemigrations stays consistent with Meta.indexes); the database
        # op creates the real Postgres GIN index and no-ops on sqlite.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name="storedentity",
                    index=django.contrib.postgres.indexes.GinIndex(
                        fields=["data"], name="ix_entities_data_gin"
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(_create_gin_index, _drop_gin_index),
            ],
        ),
    ]
