# Generated by Django 5.2.15 on 2026-06-28 19:12
#
# Adds Python-level defaults (timezone.now / version=1) to the entity timestamp +
# version columns so direct ORM creates no longer fail NOT-NULL. These are
# CALLABLE/Python defaults, so Django emits NO DDL (no ALTER COLUMN SET DEFAULT) —
# the migration is a faithful state record that is a no-op against the real DB
# schema, matching the managed-table note in models.py (prod applies --fake; the
# repository still sets these columns explicitly to carry publish-time provenance).

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heldentity",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="storedentity",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="storedentity",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="storedentity",
            name="version",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="storedversion",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
