# Generated by Django 5.2.15 on 2026-07-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0002_alter_heldentity_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="storedentity",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
