# Generated by Django 5.2.15 on 2026-08-11 00:00

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0003_storedentity_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="storedentity",
            name="merged_into",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name="EntityMerge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("survivor_iri", models.TextField(db_index=True)),
                ("duplicate_iris", models.JSONField(default=list)),
                ("duplicate_snapshots", models.JSONField(default=dict)),
                ("survivor_snapshot_before", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("complete", "Complete")],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("reference_manifest", models.JSONField(default=list)),
                ("author_id", models.TextField()),
                ("change_description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "entity_merges",
                "ordering": ["-created_at"],
            },
        ),
    ]
