"""Precision and recall against the labelled set, and the zero-false-positive gate.

A false positive here is a wrong bind: a named individual publicly attached to a
corruption case they had nothing to do with. One is a build failure.

THE THREE FIXTURES. `entity_candidates.json` holds `/api/search/?type=entity`
responses for 142 names (7,882 rows, `id`/`title`/`score` only).
`entity_documents.json` holds one trimmed `/api/entities/<ref>` document per
entity the resolver would bind (40), keyed by IRI. `entity_labels.jsonl` holds the
142 labelled rows. All three are frozen prod reads, regenerated by
`scripts/capture_entity_candidates.py`, which is what makes this file offline and
deterministic. The names are real -- 138 come from the July A/B extraction logs, so
the distribution matches what the LLM actually emits, dirt and all.

TWO CAPTURES, NOT ONE, because search alone cannot reach the Election Commission
misses: `/api/search/` returns no field separating a real case subject from a 2079
candidate record sharing the name, so no amount of scoring work gets there. The
entity document is what does.

HOW A LABEL IS ALLOWED TO BE MADE. The label must not come from the resolver's own
logic, or the gate proves nothing. `resolve` reads exactly three strings per
candidate -- `title.ne`, `title.en`, and the IRI slug -- so every label rests on
something else: a caseworker's existing bind on the source case, or the full prod
entity document. That is the property that makes this a measurement and not a
mirror.

NEVER CLOSE A PRECISION GAP BY EDITING A LABEL OR MOVING `MIN_BIND_SCORE`. If you
change a fixture, re-measure every figure below. `test_the_labelled_set_is_whole`
and `test_the_gate_actually_exercises_binding` exist because the fixtures are
generated: they assert the row count is exactly 142, that enough rows really reach
BIND, and that the veto rows are present BY NAME. Without them, a truncated
fixture -- or deleting the five election-record rows to clear a red build -- passes
and prints "precision 1.000" over a set that proves nothing.

THREE PIPELINES ARE MEASURED HERE AND THEY DO NOT SCORE THE SAME. Read which is
which before quoting a number out of this file.

  RESOLVER-ONLY (`_decisions`) is the matcher's ceiling: `resolve` matches names,
  then `apply_document_veto` refuses Election Commission candidate records. NOT
  what ships. Precision 1.000, recall 0.846.

  STRICT PRODUCTION (`_production_plans(strict=True)`) is `plan_case_entities`
  with the vetoes respected. It now equals the matcher exactly -- binding every
  section the API accepts, rather than `related` alone, cost nothing in precision
  and took recall from 0.667 to 0.846. Precision 1.000.

  PERMISSIVE PRODUCTION (`_production_plans(strict=False)`) is THE DEFAULT: an
  ambiguity or a veto binds the best-scoring candidate anyway. Precision 0.872,
  recall 0.872 -- +1 correct bind and +5 wrong ones against strict, which is the
  accepted cost of binding everything that matched.

All three are printed with their name attached. The one to quote when asking what
the enricher does by default is the permissive row -- and its precision is not
1.000, deliberately.
"""
import json
from functools import lru_cache
from pathlib import Path

import pytest

from casework.enrich_related_entities import plan_case_entities
from casework.entity_resolver import (
    BIND,
    NO_MATCH,
    REVIEW,
    apply_document_veto,
    resolve,
)

FIXTURES = Path(__file__).parent / "fixtures"


# Cached: `entity_candidates.json` is 63k lines and several tests below walk the
# whole labelled set twice each. No test mutates what these return.
@lru_cache(maxsize=1)
def load_labels():
    return [json.loads(line) for line in
            (FIXTURES / "entity_labels.jsonl").read_text(encoding="utf-8").splitlines()
            if line.strip()]


@lru_cache(maxsize=1)
def load_candidates():
    return json.loads((FIXTURES / "entity_candidates.json").read_text(encoding="utf-8"))


@lru_cache(maxsize=1)
def load_documents():
    return json.loads((FIXTURES / "entity_documents.json").read_text(encoding="utf-8"))


def _decisions():
    """Every labelled row through the full two-step decision, offline.

    The frozen documents stand in for `CaseworkApi.get_entity`; the veto is only
    consulted for a BIND, exactly as the caller does it, so no test depends on a
    document for a row that never reaches that step.
    """
    candidates, documents = load_candidates(), load_documents()
    for row in load_labels():
        decision = resolve(row["extracted"], candidates.get(row["extracted"], []))
        if decision.is_bind:
            assert decision.nes_id in documents, (
                f"no frozen document for {decision.nes_id} -- re-run "
                "scripts/capture_entity_candidates.py")
            decision = apply_document_veto(decision, documents[decision.nes_id])
        yield row, decision


class _FrozenApi:
    """`CaseworkApi`'s two read methods, served from the frozen captures.

    `plan_case_entities` only ever calls `search_entities` and `get_entity`, so
    the production path can be measured offline and deterministically against the
    same two files the resolver-only path uses. A missing document raises, which
    is what we want: the gate should fail loudly rather than quietly measure the
    fail-closed branch of the document veto.
    """

    def __init__(self, candidates, documents):
        self._candidates = candidates
        self._documents = documents

    def search_entities(self, name):
        return self._candidates.get(name, [])

    def get_entity(self, nes_id):
        return self._documents[nes_id]


# `plan_case_entities` refuses any case that is not DRAFT and any payload with no
# `entities` key, both before it looks at a single name. One synthetic case per
# row, with no existing binds, so the already-bound skip never interferes and
# each row's plan stands alone.
_SYNTHETIC_CASE = {"slug": "labelled-set", "state": "DRAFT", "entities": []}


def extracted_relationship_type(row):
    """The `relationship_type` the extractor emits for this row, in production.

    Derived from the labelled target, not guessed: `SYSTEM_PROMPT` Part 1 tells
    the LLM to emit districts, municipalities and provinces as
    `relationship_type="location"`, and Part 2 covers everything else as
    `"related"`. So a row whose labelled bind target is a `location/*` entity is
    a location-typed extraction in production.

    Rows with no target (REVIEW / NO_MATCH labels) are typed `related`, which is
    the CONSERVATIVE direction for a precision gate: `related` is the permissive
    path, so those rows get the full chance to produce a wrong bind rather than
    being refused before the search.
    """
    target = row.get("expected_nes_id") or ""
    return "location" if "/entity/location/" in target else "related"


def _production_plans(strict=False):
    """Every labelled row through `plan_case_entities` -- the shipped pipeline.

    One row per plan, so `plan_case_entities`' already-bound dedupe cannot drop
    the second of two rows that resolve to the same IRI (`सोरु गाउँपालिका` and
    `सोरु गाउँपालिका, मुगु` both target one municipality).

    `strict` selects which pipeline is being measured, and the two score very
    differently -- pass it explicitly at every call site rather than relying on
    the default, so a printed figure can never be read against the wrong mode.
    """
    api = _FrozenApi(load_candidates(), load_documents())
    for row in load_labels():
        item = {"entity_name": row["extracted"],
                "relationship_type": extracted_relationship_type(row),
                "notes": "measured by the labelled gate"}
        yield row, item, plan_case_entities(
            api, _SYNTHETIC_CASE, "W/\"labelled\"", [item], strict=strict)


# The labelled set's exact size. Asserted, not inferred, because
# `entity_labels.jsonl` is regenerated by a gitignored script: a partial write --
# or someone deleting the six ECN rows to clear a red build -- would otherwise
# leave both gate tests passing and printing "precision 1.000" over a set that
# proves nothing. Change this only alongside a deliberate change to the fixture.
EXPECTED_LABEL_COUNT = 142
# The six rows the document veto exists for. Named individually so removing one
# is a test failure and not a silent improvement in the numbers. Each is the only
# NES entity with that name, and each is an Election Commission 2079 candidate
# record for a ward the case has nothing to do with.
ECN_VETO_ROWS = (
    "टोपेन्द्र खनाल",
    "नन्दलाल दास",
    "याङजी शेर्पा",
    "राज बहादुर बम",
    # nec-candidate-id, an ELECTED ward head rather than a candidate. The veto
    # keyed on ecn-candidate-id alone until 2026-08-03 and let this through.
    "तेजनाथ पौडेल",
)
# `मिङमा ल्हमु शेर्पा` used to sit in ECN_VETO_ROWS above, and it is deliberately
# no longer there. It no longer reaches BIND at all: the extraction spells it
# ल्हमु where NES stores ल्हामु, and an inserted ा stopped folding when
# romanisation was restricted to cross-script matching (see `tokens_equal`).
# It is pinned below rather than deleted, so that the day someone widens the fold
# again this gate says so instead of quietly regaining a bind.
#
# Honest cost: the document veto now has FIVE rows exercising it, not six.
NO_LONGER_REACHES_THE_DOCUMENT_VETO = (
    "मिङमा ल्हमु शेर्पा",
)
# Rows the PROVINCE veto holds: the candidate IRI asserts a province the extracted
# name never mentions. Separate from ECN_VETO_ROWS because a different veto fires,
# and pure -- no document is consulted.
PROVINCE_VETO_ROWS = (
    "वन तथा वातावरण मन्त्रालय",
)
# Rows the UNQUALIFIED-INSTITUTION veto holds: an institution-type name that NES
# also holds with a locality appended, so the record it matches is the
# district-less bucket. Structural, and pure -- no document is consulted.
#
# This row is LABELLED BIND and is deliberately no longer bound. The label rests
# on a human's bind for one specific case; the resolver would produce the same
# bind for a case in any other district, and Nepal has one land-revenue office
# per district. Costing this row is why resolver-only recall is 0.846 and not
# 0.872.
BUCKET_VETO_ROWS = (
    "मालपोत कार्यालय",
)
# Rows production refuses BEFORE searching, because the extractor types them
# `location` and `plan_case_entities` only ever binds `related`. Named so the
# gate breaks if someone widens that allow-list without re-reading the product
# decision behind it -- whether to bind locations is open and out of scope here.
# All nine are `location/*` bind targets; the resolver binds seven of them.
LOCATION_TYPED_ROWS = (
    "अदानचुली गाउँपालिका",
    "छायाँनाथ रारा नगरपालिका",
    "तामाकोशी गाउँपालिका",
    "नवराजपुर गाउँपालिका",
    "नागार्जुन नगरपालिका - काठमाडौं",
    "रामधुनी नगरपालिका",
    "शारदा नगरपालिका",
    "सोरु गाउँपालिका",
    "सोरु गाउँपालिका, मुगु",
)


def test_the_labelled_set_is_whole():
    """Guards every other test in this file. A gate that cannot fail is not a gate."""
    rows = load_labels()
    assert len(rows) == EXPECTED_LABEL_COUNT, (
        f"expected {EXPECTED_LABEL_COUNT} labelled rows, found {len(rows)} -- the "
        "fixture is truncated, and the precision below would be measured over a "
        "subset")

    extracted = {row["extracted"] for row in rows}
    assert len(extracted) == EXPECTED_LABEL_COUNT, "duplicate rows in the labelled set"

    missing = [name for name in
               ECN_VETO_ROWS + PROVINCE_VETO_ROWS + BUCKET_VETO_ROWS + LOCATION_TYPED_ROWS
               if name not in extracted]
    assert not missing, (
        f"veto regression rows are gone from the labelled set: {missing}. These are "
        "the namesake election records, province-scoped bodies and unqualified "
        "institution buckets the vetoes exist to refuse, plus the location-typed "
        "rows production refuses before searching; without them the gate no longer "
        "tests them")

    # LOCATION_TYPED_ROWS is derived, not hand-maintained: it must be exactly the
    # rows `extracted_relationship_type` types `location`, or the production
    # measurement below is scoring a different population than it names.
    typed = {row["extracted"] for row in rows
             if extracted_relationship_type(row) == "location"}
    assert typed == set(LOCATION_TYPED_ROWS), (
        "LOCATION_TYPED_ROWS no longer matches the labelled targets: "
        f"only in the list {set(LOCATION_TYPED_ROWS) - typed}, only in the "
        f"fixture {typed - set(LOCATION_TYPED_ROWS)}")

    # Every row carries the four fields the gate reads, and an audit trail.
    for row in rows:
        assert row.get("provenance"), f"{row['extracted']!r} has no provenance"
        assert row["expected_verdict"] in (BIND, "REVIEW", "NO_MATCH"), row
        if row["expected_verdict"] == BIND:
            assert row["expected_nes_id"], f"{row['extracted']!r} binds to nothing"
        else:
            assert row["expected_nes_id"] is None, (
                f"{row['extracted']!r} is not a BIND but carries an id")


def test_the_gate_actually_exercises_binding():
    """The set must contain rows that reach BIND, and rows the veto downgrades.

    Without this, a labelled set of nothing but NO_MATCH rows scores a perfect
    precision of 1.000 and the gate is decoration.
    """
    rows = list(_decisions())
    assert len(rows) == EXPECTED_LABEL_COUNT

    bound = [r for r, d in rows if d.verdict == BIND]
    assert len(bound) >= 30, f"only {len(bound)} rows reached BIND; the gate is vacuous"

    should_bind = [r for r, _ in rows if r["expected_verdict"] == BIND]
    assert len(should_bind) >= 30, f"only {len(should_bind)} rows are labelled BIND"

    # Every ECN row must be present AND actually downgraded by the veto — proof
    # the veto is load-bearing rather than a no-op that happens to look right.
    by_name = {r["extracted"]: d for r, d in rows}
    for name in ECN_VETO_ROWS:
        assert name in by_name, f"{name!r} missing from the measured set"
        assert by_name[name].verdict == REVIEW, (
            f"{name!r} was not downgraded — the document veto is not firing")
        assert by_name[name].nes_id is None

    # Pinned so a widened fold cannot silently turn this back into a bind.
    for name in NO_LONGER_REACHES_THE_DOCUMENT_VETO:
        assert name in by_name, f"{name!r} missing from the measured set"
        assert by_name[name].verdict == NO_MATCH, (
            f"{name!r} reached {by_name[name].verdict} -- it should not score at "
            "all. If the matra fold was widened, re-check that कमल थापा still "
            "cannot bind a कमला थापा entity before accepting this.")

    # The province veto is pure, so it must fire inside resolve() itself and name
    # the province, otherwise a caseworker cannot tell what to check.
    for name in PROVINCE_VETO_ROWS:
        assert name in by_name, f"{name!r} missing from the measured set"
        decision = by_name[name]
        assert decision.verdict == REVIEW, (
            f"{name!r} was not held — the province veto is not firing")
        assert decision.nes_id is None
        assert "province" in decision.reason, decision.reason

    # The unqualified-institution veto is pure and structural, so it must fire
    # inside resolve() and name the qualified sibling the caseworker should add.
    for name in BUCKET_VETO_ROWS:
        assert name in by_name, f"{name!r} missing from the measured set"
        decision = by_name[name]
        assert decision.verdict == REVIEW, (
            f"{name!r} was not held — the unqualified-institution veto is not firing")
        assert decision.nes_id is None
        assert "unqualified institution name" in decision.reason, decision.reason


def test_zero_false_positives_across_the_labelled_set():
    rows = list(_decisions())
    assert len(rows) == EXPECTED_LABEL_COUNT, "labelled set truncated"

    false_positives = []
    for row, decision in rows:
        if decision.verdict != BIND:
            continue
        if row["expected_verdict"] != BIND or decision.nes_id != row["expected_nes_id"]:
            false_positives.append(
                f"{row['extracted']!r} bound to {decision.nes_id} "
                f"(expected {row['expected_verdict']} {row['expected_nes_id']}) "
                f"-- {row['provenance']}")
    assert not false_positives, (
        "WRONG BINDS — each one attaches a named individual to a case they may have "
        "nothing to do with:\n" + "\n".join(false_positives))


def _score(label, should_bind, bound_pairs):
    """Print one named precision/recall pair and return it.

    `label` is not decoration. Two pipelines are measured in this file and they
    score differently, so every printed figure carries the name of the pipeline
    it describes -- see the module docstring.
    """
    correct = [1 for expected, got in bound_pairs if expected == got]
    # No `or 1.0` fallbacks: an empty numerator or denominator here means the
    # fixture is broken, and a division error is a better outcome than a
    # confident 1.000 over nothing.
    precision = len(correct) / len(bound_pairs)
    recall = len(correct) / should_bind
    print(f"\n{label}")
    print(f"  {should_bind} labelled BIND rows; bound {len(bound_pairs)}, "
          f"correct {len(correct)}")
    print(f"  precision {precision:.3f}  recall {recall:.3f}")
    return precision, recall


def test_resolver_only_precision_and_recall_are_reported():
    """The MATCHER'S CEILING, not the shipped pipeline.

    `resolve` + `apply_document_veto` over all 142 rows. This figure ignores the
    `related`-only allow-list in `plan_case_entities`, so it counts binds
    production refuses before it searches. Quote
    `test_production_precision_and_recall_are_reported` for what ships.
    """
    rows = list(_decisions())
    assert len(rows) == EXPECTED_LABEL_COUNT, "labelled set truncated"
    should_bind = sum(1 for r, _ in rows if r["expected_verdict"] == BIND)
    bound_pairs = [(r["expected_nes_id"] if r["expected_verdict"] == BIND else None,
                    d.nes_id)
                   for r, d in rows if d.verdict == BIND]
    precision, _recall = _score(
        "RESOLVER-ONLY (matcher ceiling; NOT what production runs)",
        should_bind, bound_pairs)
    # Precision is the gate. Recall is reported, never asserted upward — the
    # threshold is not tuned to raise it.
    assert precision == 1.0


def _production_score(label, strict):
    plans = list(_production_plans(strict=strict))
    assert len(plans) == EXPECTED_LABEL_COUNT, "labelled set truncated"
    should_bind = sum(1 for r, _i, _p in plans if r["expected_verdict"] == BIND)
    bound_pairs = [
        (row["expected_nes_id"] if row["expected_verdict"] == BIND else None,
         decision.nes_id)
        for row, _item, plan in plans
        for _name, decision, _notes in plan.bound
    ]
    return _score(label, should_bind, bound_pairs)


def test_strict_production_precision_and_recall_are_reported():
    """`--strict`: every section binds, but a veto still refuses.

    Precision is the gate here, and it is perfect -- strict mode reaches the
    matcher's own ceiling, because widening the sections from `related`-only to
    all nine cost nothing in precision. It is the honest zero-false-positive
    pipeline, and `--strict` is the flag that runs it.
    """
    precision, recall = _production_score(
        "STRICT PRODUCTION (--strict: all sections, vetoes respected)", strict=True)
    assert precision == 1.0
    # Pinned so the section widening cannot silently regress. The old
    # `related`-only pipeline bound 26 of 39 (recall 0.667); binding every
    # section the API accepts takes that to 33 of 39 with precision untouched.
    assert recall == pytest.approx(33 / 39, abs=1e-4)


def test_permissive_production_precision_and_recall_are_reported():
    """THE DEFAULT: every matched name binds, ambiguities and vetoes included.

    This is the mode that ships by default, and its precision is NOT 1.0 -- that
    is the accepted, requested cost of binding everything that matched. The
    figures are asserted as a regression floor so the number cannot quietly get
    worse, never as a target.

    Priced against strict, on this set, the trade is: +1 correct bind, +5
    incorrect ones. Both directions are real and both are printed.
    """
    precision, recall = _production_score(
        "PERMISSIVE PRODUCTION (default: promotes ambiguities and vetoes)",
        strict=False)
    assert precision == pytest.approx(34 / 39, abs=1e-4)
    assert recall == pytest.approx(34 / 39, abs=1e-4)


def test_every_incorrect_permissive_bind_is_an_election_record():
    """WHERE the default mode's precision goes, named row by row.

    All five wrong binds are Election Commission candidate/ward-head records --
    not ambiguities between namesakes, which is where the risk was expected to
    be. That makes the election-record veto the one worth reinstating first if
    the precision cost turns out to matter, and it is why this is pinned by NAME:
    a sixth wrong bind, or a wrong bind from a different cause, fails here rather
    than being absorbed into the precision figure above.
    """
    wrong = {row["extracted"]
             for row, _item, plan in _production_plans(strict=False)
             for _name, decision, _notes in plan.bound
             if (row["expected_nes_id"] if row["expected_verdict"] == BIND
                 else None) != decision.nes_id}
    assert wrong == set(ECN_VETO_ROWS)


def test_a_location_typed_extraction_binds_into_the_location_section():
    """The refusal this file used to pin, inverted -- deliberately.

    A `location` extraction used to be refused before any search. It now binds,
    and the section it lands in must be `location`: the whole point of taking the
    section from the extraction is that a district does not get filed as a
    related party. Seven of these nine rows resolve; the two that do not are a
    matcher limit, not a scope refusal, so the count is asserted on the rows
    EXERCISED rather than on the rows bound.
    """
    exercised = 0
    for row, item, plan in _production_plans(strict=False):
        if item["relationship_type"] != "location":
            continue
        exercised += 1
        sections = {i["relationship_type"] for i in plan.patch_items}
        assert sections <= {"location"}, (
            f"{row['extracted']!r} was extracted as a location but planned a "
            f"{sections - {'location'}} bind")
        for item_ in plan.patch_items:
            assert "outcome" not in item_, (
                f"{row['extracted']!r} carries an outcome; that is legal only on "
                "an accused bind and the DB CHECK constraint will reject it")
    assert exercised == len(LOCATION_TYPED_ROWS), (
        f"expected {len(LOCATION_TYPED_ROWS)} location-typed rows, "
        f"exercised {exercised}")


def test_strict_production_binds_exactly_what_the_resolver_binds():
    """With the sections widened, strict production IS the matcher.

    It used to be a strict subset -- the `related`-only allow-list refused seven
    location rows the resolver bound. Nothing refuses them now, so the two sets
    are equal, and the resolver-only zero-false-positive gate covers strict
    production exactly.
    """
    resolver_bound = {row["extracted"] for row, decision in _decisions()
                      if decision.verdict == BIND}
    strict_bound = {row["extracted"]
                    for row, _item, plan in _production_plans(strict=True)
                    if plan.bound}
    assert strict_bound == resolver_bound


def test_permissive_production_binds_a_superset_of_strict_production():
    """The default mode only ever ADDS binds -- it never loses one.

    Promotion turns a REVIEW into a BIND; it must not disturb a name that already
    bound cleanly. If this ever failed, permissive mode would be trading away
    correct binds for uncertain ones rather than adding to them.
    """
    strict_bound = {row["extracted"]
                    for row, _item, plan in _production_plans(strict=True)
                    if plan.bound}
    permissive_bound = {row["extracted"]
                        for row, _item, plan in _production_plans(strict=False)
                        if plan.bound}
    assert strict_bound < permissive_bound
    assert permissive_bound - strict_bound == set(ECN_VETO_ROWS) | {"मालपोत कार्यालय"}
