"""Precision and recall against the labelled set, and the zero-false-positive gate.

A false positive here is a wrong bind: a named individual publicly attached to a
corruption case they had nothing to do with. One is a build failure.

The fixtures and the labelling method are described in `fixtures/README.md`. The
labels come from evidence `resolve` cannot read -- the full prod entity document
and the binds already on the source case -- so this measures the resolver rather
than mirroring it.

The pipeline under test is the two-step one a caller uses, not `resolve` alone:
`resolve` matches names, then `apply_document_veto` reads the bound entity's
document and refuses Election Commission candidate records. Measuring `resolve`
on its own scores 0.872, because the name matcher cannot tell a namesake ward
candidate from the official a case names -- `/api/search/` does not return the
field that would say.
"""
import json
from pathlib import Path

from casework.entity_resolver import BIND, REVIEW, apply_document_veto, resolve

FIXTURES = Path(__file__).parent / "fixtures"


def load_labels():
    return [json.loads(line) for line in
            (FIXTURES / "entity_labels.jsonl").read_text(encoding="utf-8").splitlines()
            if line.strip()]


def load_candidates():
    return json.loads((FIXTURES / "entity_candidates.json").read_text(encoding="utf-8"))


def load_documents():
    return json.loads((FIXTURES / "entity_documents.json").read_text(encoding="utf-8"))


def _decisions():
    """Every labelled row through the full two-step decision, offline.

    The frozen documents stand in for `CaseworkApi.get_entity`; the veto is only
    consulted for a BIND, exactly as the caller does it, so no test depends on a
    document for a row that never reaches that step.
    """
    candidates, documents = load_candidates(), load_documents()
    for row in load_labels():
        decision = resolve(row["extracted"], candidates.get(row["extracted"], []))
        if decision.is_bind:
            assert decision.nes_id in documents, (
                f"no frozen document for {decision.nes_id} -- re-run "
                "scripts/capture_entity_candidates.py")
            decision = apply_document_veto(decision, documents[decision.nes_id])
        yield row, decision


# The labelled set's exact size. Asserted, not inferred, because
# `entity_labels.jsonl` is regenerated by a gitignored script: a partial write --
# or someone deleting the five ECN rows to clear a red build -- would otherwise
# leave both gate tests passing and printing "precision 1.000" over a set that
# proves nothing. Change this only alongside a deliberate change to the fixture.
EXPECTED_LABEL_COUNT = 142
# The five rows the document veto exists for. Named individually so removing one
# is a test failure and not a silent improvement in the numbers. Each is the only
# NES entity with that name, and each is an Election Commission 2079 candidate
# record for a ward the case has nothing to do with.
ECN_VETO_ROWS = (
    "टोपेन्द्र खनाल",
    "नन्दलाल दास",
    "मिङमा ल्हमु शेर्पा",
    "याङजी शेर्पा",
    "राज बहादुर बम",
    # nec-candidate-id, an ELECTED ward head rather than a candidate. The veto
    # keyed on ecn-candidate-id alone until 2026-08-03 and let this through.
    "तेजनाथ पौडेल",
)
# Rows the PROVINCE veto holds: the candidate IRI asserts a province the extracted
# name never mentions. Separate from ECN_VETO_ROWS because a different veto fires,
# and pure -- no document is consulted.
PROVINCE_VETO_ROWS = (
    "वन तथा वातावरण मन्त्रालय",
)


def test_the_labelled_set_is_whole():
    """Guards every other test in this file. A gate that cannot fail is not a gate."""
    rows = load_labels()
    assert len(rows) == EXPECTED_LABEL_COUNT, (
        f"expected {EXPECTED_LABEL_COUNT} labelled rows, found {len(rows)} -- the "
        "fixture is truncated, and the precision below would be measured over a "
        "subset")

    extracted = {row["extracted"] for row in rows}
    assert len(extracted) == EXPECTED_LABEL_COUNT, "duplicate rows in the labelled set"

    missing = [name for name in ECN_VETO_ROWS + PROVINCE_VETO_ROWS
               if name not in extracted]
    assert not missing, (
        f"veto regression rows are gone from the labelled set: {missing}. These are "
        "the namesake election records and province-scoped bodies the vetoes exist "
        "to refuse; without them the gate no longer tests them")

    # Every row carries the four fields the gate reads, and an audit trail.
    for row in rows:
        assert row.get("provenance"), f"{row['extracted']!r} has no provenance"
        assert row["expected_verdict"] in (BIND, "REVIEW", "NO_MATCH"), row
        if row["expected_verdict"] == BIND:
            assert row["expected_nes_id"], f"{row['extracted']!r} binds to nothing"
        else:
            assert row["expected_nes_id"] is None, (
                f"{row['extracted']!r} is not a BIND but carries an id")


def test_the_gate_actually_exercises_binding():
    """The set must contain rows that reach BIND, and rows the veto downgrades.

    Without this, a labelled set of nothing but NO_MATCH rows scores a perfect
    precision of 1.000 and the gate is decoration.
    """
    rows = list(_decisions())
    assert len(rows) == EXPECTED_LABEL_COUNT

    bound = [r for r, d in rows if d.verdict == BIND]
    assert len(bound) >= 30, f"only {len(bound)} rows reached BIND; the gate is vacuous"

    should_bind = [r for r, _ in rows if r["expected_verdict"] == BIND]
    assert len(should_bind) >= 30, f"only {len(should_bind)} rows are labelled BIND"

    # Every ECN row must be present AND actually downgraded by the veto — proof
    # the veto is load-bearing rather than a no-op that happens to look right.
    by_name = {r["extracted"]: d for r, d in rows}
    for name in ECN_VETO_ROWS:
        assert name in by_name, f"{name!r} missing from the measured set"
        assert by_name[name].verdict == REVIEW, (
            f"{name!r} was not downgraded — the document veto is not firing")
        assert by_name[name].nes_id is None

    # The province veto is pure, so it must fire inside resolve() itself and name
    # the province, otherwise a caseworker cannot tell what to check.
    for name in PROVINCE_VETO_ROWS:
        assert name in by_name, f"{name!r} missing from the measured set"
        decision = by_name[name]
        assert decision.verdict == REVIEW, (
            f"{name!r} was not held — the province veto is not firing")
        assert decision.nes_id is None
        assert "province" in decision.reason, decision.reason


def test_zero_false_positives_across_the_labelled_set():
    rows = list(_decisions())
    assert len(rows) == EXPECTED_LABEL_COUNT, "labelled set truncated"

    false_positives = []
    for row, decision in rows:
        if decision.verdict != BIND:
            continue
        if row["expected_verdict"] != BIND or decision.nes_id != row["expected_nes_id"]:
            false_positives.append(
                f"{row['extracted']!r} bound to {decision.nes_id} "
                f"(expected {row['expected_verdict']} {row['expected_nes_id']}) "
                f"-- {row['provenance']}")
    assert not false_positives, (
        "WRONG BINDS — each one attaches a named individual to a case they may have "
        "nothing to do with:\n" + "\n".join(false_positives))


def test_precision_and_recall_are_reported():
    rows = list(_decisions())
    assert len(rows) == EXPECTED_LABEL_COUNT, "labelled set truncated"
    should_bind = [r for r, _ in rows if r["expected_verdict"] == BIND]
    did_bind = [(r, d) for r, d in rows if d.verdict == BIND]
    correct = [1 for r, d in did_bind
               if r["expected_verdict"] == BIND and d.nes_id == r["expected_nes_id"]]
    # No `or 1.0` fallbacks: an empty numerator or denominator here means the
    # fixture is broken, and a division error is a better outcome than a
    # confident 1.000 over nothing.
    precision = len(correct) / len(did_bind)
    recall = len(correct) / len(should_bind)
    print(f"\nlabelled set: {len(rows)} names, {len(should_bind)} should bind")
    print(f"bound {len(did_bind)}, correct {len(correct)}")
    print(f"precision {precision:.3f}  recall {recall:.3f}")
    # Precision is the gate. Recall is reported, never asserted upward — the
    # threshold is not tuned to raise it.
    assert precision == 1.0
