# Generated by Django 5.2.9 on 2026-06-18 00:05

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_create_article_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 0),
                    ("paragraph", 1),
                    ("image", 4),
                    ("quote", 5),
                    ("document", 6),
                    ("embed", 7),
                    ("case", 10),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "icon": "title"},
                    ),
                    1: ("wagtail.blocks.RichTextBlock", (), {"icon": "pilcrow"}),
                    2: ("content.blocks.APIImageChooserBlock", (), {}),
                    3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("caption", 3)]],
                        {},
                    ),
                    5: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    6: (
                        "content.blocks.APIDocumentChooserBlock",
                        (),
                        {"icon": "doc-full-inverse"},
                    ),
                    7: ("wagtail.embeds.blocks.EmbedBlock", (), {"icon": "media"}),
                    8: ("content.blocks.CaseChooserBlock", (), {}),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional context shown alongside the case",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("case", 8), ("note", 9)]],
                        {},
                    ),
                },
            ),
        ),
    ]
