# Generated by Django 5.2.15 on 2026-07-24 16:36

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


def forwards_copy_links(apps, schema_editor):
    """Copy existing ``ArticlePage.related_cases`` M2M links into the through table.

    Runs while the old M2M field still exists (before ``RemoveField``), so no
    related-case links are lost when the field is dropped. Reads only the case
    PKs (not full Case rows), pins the migration's DB alias so routed
    multi-DB setups stay consistent, and inserts in bounded batches.
    """
    ArticlePage = apps.get_model("content", "ArticlePage")
    ArticlePageRelatedCase = apps.get_model("content", "ArticlePageRelatedCase")
    alias = schema_editor.connection.alias

    rows = []
    for article in ArticlePage.objects.using(alias).iterator():
        for case_id in article.related_cases.values_list("pk", flat=True):
            rows.append(
                ArticlePageRelatedCase(article_page_id=article.pk, case_id=case_id)
            )
    ArticlePageRelatedCase.objects.using(alias).bulk_create(
        rows, batch_size=1000, ignore_conflicts=True
    )


def backwards_copy_links(apps, schema_editor):
    """Restore through-table links back into the M2M field on reverse.

    Groups links by article so the M2M is repopulated with one ``add()`` per
    article (rather than a per-row ``get()`` + ``add()``), and pins the DB alias.
    """
    ArticlePage = apps.get_model("content", "ArticlePage")
    ArticlePageRelatedCase = apps.get_model("content", "ArticlePageRelatedCase")
    alias = schema_editor.connection.alias

    case_ids_by_article = {}
    for article_id, case_id in ArticlePageRelatedCase.objects.using(alias).values_list(
        "article_page_id", "case_id"
    ):
        case_ids_by_article.setdefault(article_id, []).append(case_id)

    for article in ArticlePage.objects.using(alias).filter(
        pk__in=case_ids_by_article
    ):
        article.related_cases.add(*case_ids_by_article[article.pk])


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0054_banking_offence_case_type'),
        ('content', '0004_brand_newsroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePageRelatedCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_cases_through', to='content.articlepage')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cases.case')),
            ],
            options={
                'verbose_name': 'Related case',
                'verbose_name_plural': 'Related cases',
                'unique_together': {('article_page', 'case')},
            },
        ),
        migrations.RunPython(forwards_copy_links, backwards_copy_links),
        migrations.RemoveField(
            model_name='articlepage',
            name='related_cases',
        ),
    ]
