# Generated by Django 5.2.15 on 2026-07-24 16:36

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


def forwards_copy_links(apps, schema_editor):
    """Copy existing ``ArticlePage.related_cases`` M2M links into the through table.

    Runs while the old M2M field still exists (before ``RemoveField``), so no
    related-case links are lost when the field is dropped.
    """
    ArticlePage = apps.get_model("content", "ArticlePage")
    ArticlePageRelatedCase = apps.get_model("content", "ArticlePageRelatedCase")
    links = []
    for article in ArticlePage.objects.all():
        for case in article.related_cases.all():
            links.append(
                ArticlePageRelatedCase(article_page_id=article.pk, case_id=case.pk)
            )
    ArticlePageRelatedCase.objects.bulk_create(links, ignore_conflicts=True)


def backwards_copy_links(apps, schema_editor):
    """Restore through-table links back into the M2M field on reverse."""
    ArticlePage = apps.get_model("content", "ArticlePage")
    ArticlePageRelatedCase = apps.get_model("content", "ArticlePageRelatedCase")
    for link in ArticlePageRelatedCase.objects.all():
        ArticlePage.objects.get(pk=link.article_page_id).related_cases.add(link.case_id)


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0054_banking_offence_case_type'),
        ('content', '0004_brand_newsroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePageRelatedCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_cases_through', to='content.articlepage')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cases.case')),
            ],
            options={
                'verbose_name': 'Related case',
                'verbose_name_plural': 'Related cases',
                'unique_together': {('article_page', 'case')},
            },
        ),
        migrations.RunPython(forwards_copy_links, backwards_copy_links),
        migrations.RemoveField(
            model_name='articlepage',
            name='related_cases',
        ),
    ]
