# Generated by Django 5.2.15 on 2026-06-28 05:15

import ngm_service.materials.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "iri",
                    models.CharField(
                        max_length=400,
                        primary_key=True,
                        serialize=False,
                        validators=[ngm_service.materials.models.validate_material_iri],
                    ),
                ),
                ("material_type", models.CharField(db_index=True, max_length=40)),
                ("source", models.CharField(db_index=True, max_length=120)),
                ("ident", models.CharField(db_index=True, max_length=300)),
                ("data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "materials",
                "indexes": [
                    models.Index(
                        fields=["source", "material_type"],
                        name="materials_source_6833b4_idx",
                    )
                ],
            },
        ),
    ]
